### ISSUE TITLE
record the task history to a file

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1007]
As I see in the configuration document in : http://luigi.readthedocs.org/en/stable/configuration.html#task-history

"Parameters controlling storage of task history in a database
db_connection
Connection string for connecting to the task history db using sqlalchemy."

It seems that the task history can only be recorded in database like mysql or postgres, But can I record it in a file?  If so,  I do not have to connect to any db.

**Comment by leafjungle** [comment]
Right now, I am using mysql.

I find many tasks's RUNING event and DONE event are not recorded into mysql.
luigi is using sqlalchemy, it is hard to debug the reason.

**Comment by mfcabrera** [comment]
Closing this issue.  

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
