### ISSUE TITLE
Access task logs in luigid

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1008]
Hii, Luigier~~
Is it configurable to display task log in static/visualiser/index.html ?

**Comment by Tarrasch** [comment]
Task log? How long does it take and how many tasks do you have? I know there's a way to limit the number of tasks to display.

**Comment by leafjungle** [comment]
"Task log? How long does it take and how many tasks do you have? I know there's a way to limit the number of tasks to display." @Tarrasch 

I mean when a task is running, I can see its log in the website.

**Comment by Tarrasch** [comment]
Unfortunately luigi doesn't support that feature at all. :-/

**Comment by leafjungle** [comment]
@Tarrasch ,  I found an easy solution of display a log file in the website:

(1)each Task could be relative a log file, and we can create a soft link of log directory to the web container.  So a link (href to a file)  could be created to display the log file.

(2)Make the log file path be a parameter of each Task.

**Comment by erikbern** [comment]
It would be cool if logs are piped to the central scheduler yeah. We should add that at some point!

**Comment by knassiri** [comment]
+ up vote.

**Comment by hnykda** [comment]
any progress on this?

**Comment by Tarrasch** [comment]
@hnykda, there's no automatic propagation of logs, but you can now report a status summary from your worker to luigid and it will be displayed on the scheduler website.

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
