### ISSUE TITLE
Configurable number of processes used for parallel processing

### ISSUE THREAD

**Issue by riga** [spotify/luigi#1114]
When enabling parallel processing in the scheduler, a `mutliprocessing.Pool` instance is created by the worker [without arguments](https://github.com/spotify/luigi/blob/master/luigi/worker.py#L399). Hence, [the pool uses the maximum number of processes obtained via `cpu_count()`](https://docs.python.org/2/library/multiprocessing.html#module-multiprocessing.pool).

In my typical workflows where I use a local machine at work, I like to have one spare processor for some interactive tasks (e.g. some shell operations, etc). When all processors run at ~100% for let's say 6 hours, interactive working is not that much fun. So I would really appreciate an (integer) option like "max_parallel_tasks" in the [core] section.

Maybe even some sign distinction could be helpful, sth like:

``` python
...
count = cpu_count()
if count > max_parallel_tasks > 0:
    n_processes = max_parallel_tasks
elif -count < max_parallel_tasks < 0:
    n_processes = count + max_parallel_tasks # max_parallel_tasks is negative here
else:
    n_processes = count

pool = multiprocessing.Pool(n_processes)
...
```

(In that case I would choose `max_parallel_tasks: -1`)

Off-topic: Nice job guys!

**Comment by Tarrasch** [comment]
I like your idea of negative numbers. As with most features you'll have to implement it yourself though ^^

**Comment by dmyersturnbull** [comment]
+1 This is pretty critical to me as well.

@riga Have you looked at this at all? I'll take a look, but I've only just started using Luigi.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
