### ISSUE TITLE
Suggestion on RecordTarget for RDBMS

### ISSUE THREAD

**Issue by ZhijieWang** [spotify/luigi#1149]
Hi,

I saw a discussion on mailing list about fetch from postgresql. I so happen to be working on a project using both luigi and postgres. I would like to share my work and receive some feedback -- potentially making a PR to main repo.

Concerns:
In my use case, fetchall is perfect, because I always passing a query returning 1 row 1 column (i.e. 1 cell). But fetchall may not be the best for other use case. 

Fetch\* is intentionally used to check if the actual target exists. Alternatively, we could have a query specifically used to check target (for instance, use COUNT to count rows with where clause) and 1 query to return the data. But this introduce too much queries and could be hard to manage.

```
class RecordTarget(luigi.Target):
    def __init__(self, query):
        self.value = query.fetchall()

    def exists(self):
        if self.value:
            return True
        else:
            return False

class RecordExampleTask(luigi.ExternalTask):
    def output(self):
        cur = db.query(
            "SELECT * FROM test")
        return RecordTarget(cur)


class UseRecordExampleTask(luigi.Task):
    def requires(self):
       return [RecordExampleTask()]
    def run(self):
       self.requires()[0].output().value # the record rows
       return None
```

**Comment by Tarrasch** [comment]
I thought our current postgres target can do even "dated" `exists()` checks. no?

**Comment by ZhijieWang** [comment]
I think the answer is yes, by using a `marker_table`. More documentation is needed.       
However, PostgresTarget returns/initiates an connection to PostgresSQL db, and then the Task that utilizes the data performs the query. In my use case, the target actual hold the data.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
