### ISSUE TITLE
Suggestion: Warn for non-string keys or values in kwargs in <class>.from_str_params()

### ISSUE THREAD

**Issue by samuell** [spotify/luigi#1160]
I figured that when using the class method [from_str_params()](https://github.com/spotify/luigi/blob/master/luigi/task.py#L296-L310), if accidentally submitting values that are not strings, one can get hard to debug errors.

E.g. with the following snippet, where the zero in the dictionary is an int rather than a string:

``` python
import luigi

class ATask(luigi.Task):
    avalue = luigi.IntParameter()
    def output(self):
        return 'afile.txt'
    def run(self):
        with self.output().open('w') as outf:
            outf.write(str(self.avalue))

if __name__ == '__main__':
    t = ATask.from_str_params({'avalue': 0})
```

... I get the following error:

``` bash
$ python error.py 
Traceback (most recent call last):
  File "error.py", line 12, in <module>
    t = ATask.from_str_params({'avalue': 0})
  File "/home/samuel/.pyenv/versions/2.7.8/lib/python2.7/site-packages/luigi/task.py", line 297, in from_str_params
    value = param.parse_from_input(param_name, params_str[param_name])
  File "/home/samuel/.pyenv/versions/2.7.8/lib/python2.7/site-packages/luigi/parameter.py", line 296, in parse_from_input
    (param_name, "--" + param_name.replace('_', '-')))
luigi.parameter.MissingParameterException: No value for 'avalue' (--avalue) submitted and no default value has been assigned.
```

This specific error, I figured was due to the [line "if not x" in line 291 of parameter.py](https://github.com/spotify/luigi/blob/master/luigi/parameter.py#L291), which results in a "no" in this if statement, due to the integer zero value being sent.

Maybe one could add checks that all the keys and values really are string, in from_str_params()?

**Comment by samuell** [comment]
Of course, it clearly states that it expects string values, so the error was really user-caused (by me and myself), just thought it might help someone else find their mistake :)

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
