### ISSUE TITLE
how to configure beeline for hive related task :( 

### ISSUE THREAD

**Issue by yupbank** [spotify/luigi#1161]
Hey guys, it would be nice if there are more documents about configuration.

I've wasted two days on configuring the beeline and hdfs

**Comment by erikbern** [comment]
Would be awesome if you can document the things you ran into and send a PR!

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
