### ISSUE TITLE
help, tasks do not be inserted into mysql table any more.

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1213]
all the tasks will not be insert into tasks, task_events, task_parameters tables any more.

I do not know why?

(1) I checkd the amount of data in these three tables: less than 20,000.  And is there any limitations?
check: I delete some records from mysql, and the problem remains yet.

(2)mysql server is running correctly, I can login and insert/query myself.

(3)From the mysql log, no "insert" records are found recently (2 days)

(4) luigi use  sqlalchemy framework, and how can I debug the "insert" operation?

**Comment by leafjungle** [comment]
And all the done tasks will not be shown in the "Done" list of visualise any more.

I am sure the number of shown tasks is less than "max-shown-tasks".

**Comment by leafjungle** [comment]
And I have a problem:
I start luigid:
luigid --background --state-path /home/user/state_1

And I config client.cfg:
[scheduler]
state-path: /home/user/state_2

Will this cause any problem?

**Comment by Tarrasch** [comment]
command line is preferred I think.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
