### ISSUE TITLE
how to re-enable a task from the command line?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1224]
I want to re-enable a task immediately.
Is there any way to re-enable a task in the command line?

Note:
(1) the "re-enable" button in the visualiser seems does not work.
(2)I modify the client.cfg: disable-persist-seconds: 120;  And I restart the centeral scheduler.
But after 2minutes, I just receive an email, but the task is still disabled.

The email content:
xxxx failed 100 times in the last 3600 seconds, so it is being disabled for 120 seconds.
(Actually the task is disabled because of the disable-hard-timeout, not failure 100 times.)

**Comment by leafjungle** [comment]
Ahhhh.
I see in scheduler.py
def set_status(self, task, new_status, config=None):
       if task.has_excessive_failures():
            new_status = DISABLED

it means that once the task is disabled by disable-hard-timeout, it will never by re-enabled.

That is not suitable, I think.

**Comment by Tarrasch** [comment]
Can you send a PR?

**Comment by daveFNbuck** [comment]
The line of code you're referencing only applies when the task is beind set to FAILED. Nothing is preventing it from taking other statuses or being re-enabled. There isn't an easy way to re-enable it via command-line, but it can be done by scheduling the task as DISABLED (which takes control of the disable away from the scheduler and hands it to the worker) and then scheduling it as PENDING again.

You could also make the api call that the scheduler does when you click re-enable on the viz.

**Comment by Tarrasch** [comment]
For anyone happening to wonder, there's a nice UI button implemented already: https://github.com/spotify/luigi/pull/844

Let us know if you found any way to do this through CLI @leafjungle

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
