### ISSUE TITLE
unicode Bug in luigi.postgres.CopyToTable

### ISSUE THREAD

**Issue by moritzschaefer** [spotify/luigi#1239]
```
    for row in self.rows():
        n += 1
        if n % 100000 == 0:
            logger.info("Wrote %d lines", n)
        rowstr = self.column_separator.join(self.map_column(val) for val in row)
        rowstr += "\n"
        tmp_file.write(rowstr.encode('utf-8'))
```

in combination with self.map_column: 

```
def map_column(self, value):
    """
    Applied to each column of every row returned by `rows`.

    Default behaviour is to escape special characters and identify any self.null_values.
    """
    if value in self.null_values:
        return r'\\N'
    elif six.PY3:
        return default_escape(str(value))
    elif isinstance(value, unicode):
        return default_escape(value).encode('utf8')
    else:
        return default_escape(str(value))
```

in python2 leads to executing encode('utf8') twice on the "same" string, which fails obviously with non-ascii-strings.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
