### ISSUE TITLE
Highlight root tasks in UI

### ISSUE THREAD

**Issue by boosh** [spotify/luigi#1282]
There's currently no easy way of knowing which tasks in the web UI are root tasks. So if one task creates tens of sub tasks, there will be a large number of tasks in the UI but only one will actually show the entire task graph.

It'd be very useful if there was a way to filter the web UI to only show tasks that are root nodes so as to be able to easily see entire task graphs without specifically needing to know the names of those tasks.

**Comment by Tarrasch** [comment]
Agreed. Want to send a PR? :)

**Comment by boosh** [comment]
If I get chance I'll look into it (but can't make any promises...)

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
