### ISSUE TITLE
postgres - use timestamps

### ISSUE THREAD

**Issue by b-nroths** [spotify/luigi#1297]
is this backwards? https://github.com/spotify/luigi/blob/master/luigi/postgres.py#L151 

if use_db_timestamps = True then we want to insert timestamps (so run the query on line 159)

lmk, and I can make a pr to fix

**Comment by mmongeon-aa** [comment]
use_db_timestamps = True is the correct usage. If it is True, the scheduler will create a table the has a [column](https://github.com/spotify/luigi/blob/master/luigi/postgres.py#L213): `'inserted TIMESTAMP DEFAULT now()`. If False, it will create a table with no default value for TIMESTAMP, therefore the scheduler will populate the value instead of the database.

**Comment by erikbern** [comment]
i don't understand this one, but happy to reopen if this is still an issue and if you want to provide some more background
