### ISSUE TITLE
Unexpected behavior with command-line overrides of parameters with default values

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#1304]
Using the following code example as test.py:
```
import luigi

class MyTask(luigi.Task):
    param1 = luigi.IntParameter()
    param2 = luigi.BoolParameter(default=False)

    def requires(self):
        if self.param1 > 0:
            yield MyTask(self.param1 - 1)

    def complete(self):
        return False

    def run(self):
        pass

if __name__ == '__main__':
    luigi.run()
```

if I run `python test.py MyTask --param1 1` I'll see the output I expect, with the following run summary:

```
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 MyTask(param1=0, param2=False)
* 1 failed:
    - 1 MyTask(param1=1, param2=False)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====
```

but if I add `--param2` to set param2 to true in my root task, I get

```
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 MyTask(param1=0, param2=True)
* 1 failed:
    - 1 MyTask(param1=1, param2=True)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====
```

which shows that I've actually changed param2 in _all_ tasks of the same class. This is pretty far from expected and normal behavior for member parameters. I usually only expect to be able to make global changes via parameters set in Config classes. This behavior seems to be new with #1182.

**Comment by erikbern** [comment]
This is no good, we should fix

**Comment by Tarrasch** [comment]
This change was intentional. One big win of #1182 was that global and local parameters were merged. There's no difference between `--MyTask-param2` and `--param2` any more. The former will always work (in case of conflicts) while `--param2` is shorter and more convenient, otherwise there's no difference.

I suppose that we could reintroduce the old behaviour without needing to rewrite everything, but then the parsing logic would start to become complex again. 

@daveFNbuck, Don't you like that you can override variables in tasks too? It have been convenient for me a few times. Currently there's no distinction between Config classes and Tasks, which is pretty nice from an implementers point of view as well. :)

Have there been any real world use cases that's affected (negatively) by this?

**Comment by erikbern** [comment]
I see your point @Tarrasch but not sure if the new behavior is that much more logical. The old behavior wasn't super logical either tbh.

Let me think about this some more

**Comment by daveFNbuck** [comment]
@Tarrasch we have a --overwrite flag that we used to use to quickly redo a task if there was a bug in the task or while developing. It just makes complete return false. This has recently caused problems at Houzz when trying to redo a task that depends on other tasks of the same type, as it caused a big cascade of redos and actually prevented non-leaf tasks from running because they would always have incomplete requirements. It seems unsafe to ever not specify a parameter value in a task constructor under #1182. I expect this sort of behavior from global config classes, but not from object constructors. I guess we'll have to be more explicit in all of our requires functions if we want to get the desired behavior.

This sort of thing probably causes bigger problems at Houzz because most of our tasks are impala/hive queries which all share the same small set of classes and differ only in the query and a few other config options. It's a bit bizarre though. If I run a daily query with --overwrite, only the daily queries that it depends on will also become overwrite. Queries that are scheduled hourly and thus have a different class will not be re-run and neither will tables that are filled in from mapreduce jobs. You can imagine how confusing this is for the end-user who is not a programmer and only interacts with luigi by writing queries in a yaml config and running the command-line. We infer dependencies automatically from the queries, so having dependencies behave differently depending on their classes seems very random.

**Comment by Tarrasch** [comment]
@daveFNbuck I'm truly very sorry for the trouble it have caused you at Houzz. I'll get back to this issue soon. Let's see this as a blocker for 2.0.0. Thanks for raising this issue in time :)

**Comment by daveFNbuck** [comment]
Luckily this issue is limited to small manual runs at Houzz, so there wasn't too much trouble caused. Just some confused analysts trying to change some data after re-writing a query. It could even be ok with proper communication. Probably best to fix it before others get surprised by this behavior though. I'd be happy with --MyTask-param2 causing a global change and --param2 only changing the root task if that's at all possible. That should give us the best of both worlds and could limit the scope of the code change.

**Comment by Tarrasch** [comment]
> I'd be happy with --MyTask-param2 causing a global change and --param2 only changing the root task if that's at all possible.

Hmm, wouldn't be impossible to implement. But it would make code messier. Hmm, I was really hoping this simplified code would be adopted by luigi as the the one and correct way. It would also easily enable for Range* and friends to recognize it's task-parameters as local tasks. For example `RangeDaily --of MyTask --start 2013-01-01 --my-param 123` (instead of `--MyTask-my-param 123`).

**Comment by daveFNbuck** [comment]
I think the shortcut you want is a bit of a trap for upgrading users. `RangeDaily --of MyTask --start 2013-01-01 --my-param 123` is great until someone decides that RangeDaily could really use an optional `my_param` parameter and gets it through a PR. Now after upgrading I find that `RangeDaily --of MyTask --start 2013-01-01 --my-param 123` produces different results from `RangeDaily --of MyTask --start 2013-01-01 --MyTask-my-param 123`.

**Comment by Tarrasch** [comment]
> RangeDaily --of MyTask --start 2013-01-01 --my-param 123 is great until someone decides that RangeDaily could really use an optional my_param parameter and gets it through a PR.

That's a good point actually. Hmm, maybe that problem is left unsolved. Even though it would be very convenient. :-/

Currently, in HEAD, I'm pretty sure `RangeDaily --of MyTask --start 2013-01-01 --my-param 123` should give a parse error. There's no parameter `--my-param`. I however just realized a week ago a terrible bug I introduced and fixed in #1293. Basically luigi would happily swallow and ignore any unknown arguments. Maybe you haven't merged in #1293 yet?

Just out of curiosity @daveFNbuck, do you guys at Houzz use Range? If you do, how have you dealt with the issue of the `--of` task requiring parameters?

**Comment by daveFNbuck** [comment]
We don't use Range. We instead have a config-based framework that can construct tasks given a time and a config key, and all the parameters are wrapped up in the config under the key. So instead of doing `Range --of MyTask` we'll do `TaskFrontFill --task task_conf` and it'll create tasks with the right classes and times. If we need to change a parameter, that's usually done in the config before running the command. For other parameters like `--overwrite` we're limited to either running one task at a time or changing the default value in the code for one run. As our main use case is overwrite, we have other tools for just marking groups of tasks as incomplete to re-run longer periods.

**Comment by Tarrasch** [comment]
Thanks for all your feedback @daveFNbuck. Maybe we should do exactly what you suggest; Making `--x` and `--MyTask-x` semantically different and not doing any magic for `TaskParameters`*. It will probably not take more than a couple of hours for me to craft a PR (essentially reverting #1274). It would eliminate the confusing behaviour.

*Maybe we could have some magic for `--help` suggesting the global parameters of the `--of` argument though.

**Comment by erikbern** [comment]
this is resolved right?

**Comment by Tarrasch** [comment]
Yes :)
