### ISSUE TITLE
RemoteScheduler timeout needs to be configurable

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1333]
Right now, RemoteScheduler() waits for a static amount of time upon failure (30 seconds).  This should be configurable, as well as a configurable jitter should be added to reduce the thundering herd when the server has issues, similar to wait_interval and wait_jitter for Worker()

**Comment by erikbern** [comment]
sure send a pull request!

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
