### ISSUE TITLE
Python 2.7.10 Boto S3 Issue

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#1339]
With the introduction and Python 2.7.9 (and 2.7.10), Boto s3 cannot handle bucket names with . (periods) in them.

This issue has a long-running thread [here](https://github.com/boto/boto/issues/2836).

I can confirm that luigi.S3 worked with buckets containing periods for Python 2.7.6. However, it does not work with 2.7.10 (my current python installation).

It may be worth looking into how to implement the fix noted by mattse for US buckets into Luigi.s3

        if '.' in bucketName:
            conn = S3Connection(awsAccessKeyID, awsSecretKey, calling_format=OrdinaryCallingFormat())
        else:
            conn = S3Connection(awsAccessKeyID, awsSecretKey)

Alternatively, we may want to switch luigi.S3 towards boto3 as it seems to be the upcoming boto replacement.

**Comment by moe1507** [comment]
I've encountered the same problem. You can actually add the calling format to your s3 section in luigi.cfg. No need to override or subclass luigi.s3.
```
[s3]
calling_format: boto.s3.connection.OrdinaryCallingFormat
```
Any parameters in the 's3' section are passed to [boto.connect_s3](boto.s3.connection.OrdinaryCallingFormat)

**Comment by dlstadther** [comment]
@moe-m Your fix worked for me. Thanks

**Comment by vlcinsky** [comment]
Consider resolving the issue on luigi side by rewriting S3 tasks from using `boto` to `boto3`.
The reason is, that `boto` does not progress much nowdays and most effort comes into `boto3`.

You may find discussion of this topic at boto/boto#3306

The problem with buckets having dots in names is really long term problem with `boto` and I have decided to rewrite my tools to `boto3` (and it works well).
