### ISSUE TITLE
Can exception handling be extensible?

### ISSUE THREAD

**Issue by gf-atebbe** [spotify/luigi#138]
When an exception is thrown by a task, the Worker class catches this and calls the send_email function in the notifications module.  It would be great if the notification action could be extensible such that a user could add their own implementation of what to do when an exception is thrown.  This way other services such as Airbrake and/or PagerDuty could be supported without adding this code into the base project. In the current design I don't see a nice way to do this though so was hoping someone else might have some thoughts on how this could be implemented.....

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
