### ISSUE TITLE
logging configuration not causing output to stdout

### ISSUE THREAD

**Issue by jrns1001** [spotify/luigi#1401]
When using a logging config file, Luigi does not respect the argument to use stdout. It would be ideal to be able to direct different log levels to stdout/stdiin

[formatters]
keys: default

[handlers]
keys: console, logfile

[loggers]
keys: root, luigi-interface

[formatter_default]
format: %(asctime)-15s %(levelname)-8s [%(filename)s:%(lineno)s - %(funcName)10s()] - %(message)10s

[formatter_generic]
class=logging.Formatter
format=%(asctime)s %(levelname)s [%(filename)s:%(lineno)s - %(funcName)10s()] %(message)s
datefmt=

[handler_console]
class: StreamHandler
args: [sys.stdout,]
formatter: default

[handler_logfile]
class: FileHandler
args: ['/logs/workflow.log']
formatter: default

[logger_root]
level: INFO
handlers: console, logfile
qualname: root
propagate=1

[logger_luigi-interface]
level: INFO
handlers: console, logfile
qualname: luigi
propagate=1

**Comment by jrns1001** [comment]
In the [handler_console] section. The args: [sys.stdout,] parameter should allow the log to be written to stdout.

**Comment by kwilcox** [comment]
Try changing the`qualname` in `[logger_luigi-interface]` to the appropriate logger name.

```ini
[logger_luigi-interface]
level: INFO
handlers: console, logfile
qualname: luigi-interface
propagate=1
```

**Comment by Tarrasch** [comment]
Here is what I use. Though I'm a noob at logging configuration though.

```
[loggers]
keys=root,luigi

[handlers]
keys=consoleHandler

[formatters]
keys=consoleFormatter

[logger_root]
level=WARNING
handlers=consoleHandler

[logger_luigi]
level=DEBUG
handlers=consoleHandler
qualname=luigi-interface
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=consoleFormatter
args=(sys.stdout,)

[formatter_consoleFormatter]
format=%(levelname)s: %(message)s
datefmt=
```

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
