### ISSUE TITLE
Using bcolz as output format?

### ISSUE THREAD

**Issue by a-campbell** [spotify/luigi#1407]
I am interested in saving off the output of a `luigi.Task` in bcolz format. Is this currently possible?

I see that calling `.open()` on a `luigi.LocalTarget' class returns a`luigi.file.atomic_file`. Will that atomic_file behave like any other ordinary open file buffer? 

It would be great to be able to use [odo](https://github.com/blaze/odo) to write to luigi targets. I'm using [blaze](https://github.com/blaze/blaze) to run queries in my tasks. 

Thanks!

**Comment by erikbern** [comment]
yes it's a file stream, you can do anything you want with it!

you could also consider implementing a new `Format` class: https://github.com/spotify/luigi/blob/master/luigi/format.py

**Comment by twiecki** [comment]
Thanks @erikbern. For my own understanding:

Say we wanted to write to csv. One way would be to do:
```python
    def input(self):
        with self.output().open('w') as out_file:
            # create csv string using pandas
            csv = dataframe.to_csv()
            out_file.write(csv)

    def output(self):
        return luigi.LocalTarget('file.csv')
```

We could hide the complexity of having to do the conversion to string in `input()` by writing a `Format` class that would carry out the conversion implicitly and the code became:
```python
    def input(self):
        with self.output().open('w') as out_file:
            out_file.write(dataframe)

    def output(self):
        return luigi.LocalTarget('file.csv', format=MyCsvFormat)
```
?
Could you give us a pointer as how to write the `MyCsvFormat` class?

Then the second use-case I was wondering about is the use of bcolz which actually writes to a directory rather than a file. Would I point `LocalTarget` to a directory and write a `Format` class that converts to a dataframe to `bcolz` binary and back? Or would I need to write my own `LocalTarget`, `BcolzTarget`?

**Comment by erikbern** [comment]
Yeah I think everything above makes sense, except the method should be `run` not `input`. It shouldn't be too hard to put together a csv format class. If I have some time later I could do it, but can't promise.

(as a side note I've been thinking about having a shortcut where instead of writing explicitly, you just return some value. Could be useful if you have a specialized DataFrameTarget class etc)

**Comment by twiecki** [comment]
@erikbern thanks for confirming.

And to the side note: yeah, that would make more intuitive sense and not have the user deal with the internals. Although it would be kinda nice to have a very simple `Target` where I define a `.write(location)`  and `.read(location)`. I suppose that's possible already or how complex would that be? Then I could define a `TargetDataFrameCsv`, use `odo` or `bcolz`.

**Comment by erikbern** [comment]
That should be very simple. The `Target` interface really only has to implement the `exists` method – `open` is not a part of the interface so you can put arbitrary methods (eg. read/write) on the target.

**Comment by twiecki** [comment]
Ah of course, `.input()` and `.output()` just return the instance. That makes it fairly trivial actually. +1 for a lean design.

**Comment by a-campbell** [comment]
In case it helps anyone, I implemented a simple bcolz target:

```
from luigi.file import LocalFileSystem
import os
import pandas as pd
import bcolz
import luigi	

class bcolzTarget(luigi.Target):
	fs = LocalFileSystem()

	def __init__(self, path=None):
		self.path = path

	def exists(self):
		return self.fs.exists(self.path)

	def read(self, **kwargs):
		"""
		Opens bcolz ctable/carray in read-only mode.
		"""
		if self.exists():
			data = bcolz.open(self.path, mode='r', **kwargs)

			return data

	def write(self, data, **kwargs):
		"""
		Write a dataframe or bcolz ctable/carray to the specified
		filepath.
		"""
		self.makedirs()

		if isinstance(data, pd.DataFrame):
			bcolz.ctable.fromdataframe(data, rootdir=self.path)

		elif isinstance(data, (bcolz.ctable, bcolz.carray)):
			data.copy(rootdir=self.path)

		else:
			raise ValueError("Cannot convert type %s to bcolz" % type(data))

	def makedirs(self):
		"""
		Create all parent folders if they do not exist.
		"""
		normpath = os.path.normpath(self.path)
		parentfolder = os.path.dirname(normpath)
		if parentfolder:
			try:
				os.makedirs(parentfolder)
			except OSError:
				pass
```

I'd love to beef this up and open a PR sometime in the future.

**Comment by erikbern** [comment]
nice! sure put it in luigi.contrib!

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
