### ISSUE TITLE
How to control the parallelism of each jobs?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1454]
For example, I have a job: 
A(x=1) require B(x=1) and C(x=1);   B(x=1) require D(x=1)
this job will be triggered in crontab, like this:
job1: A(x=1) require B(x=1) and C(x=1);   B(x=1) require D(x=1)
job2: A(x=2) require B(x=2) and C(x=2);   B(x=2) require D(x=2)
job3: A(x=3) require B(x=3) and C(x=3);   B(x=3) require D(x=3)
...

I mean , if job1 is running, all the tasks in job2 should be pending after it is triggered. how to control that?

I found a way: make D(x=2) requires A(x=1), but that is really a bad solution.

I found it is very hard to control by "resources".

**Comment by Tarrasch** [comment]
Can you format your issue with markdown? It's hard to read.

Also what is the thing with crontabs specifying dependencies? I'm a bit confused by your question. Can you clarify please? Thanks. :)

**Comment by leafjungle** [comment]
@Tarrasch , I mean when a job is running, other jobs of different luigi parameters should not run at the same time.
==============
I know that "resources" is used for controlling the parallelism of tasks, but not jobs.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
