### ISSUE TITLE
Proposal: redshift.CreateTableAs and redshift.CreateView

### ISSUE THREAD

**Issue by ybroze** [spotify/luigi#1459]
@dlstadther, @ddaniels888, @steenzout, @rantav

At TodayTix, we've built some additional tasks for creating derived tables and views within Redshift: `CreateTableAs` and `CreateView`. Does anybody else have tasks like these or plans to incorporate upstream?

If not, I'd be happy to flesh them out, test them, and submit a PR.

**Comment by dlstadther** [comment]
@ybroze I do not presently have any tasks nor plans to use these. However, if these are features that you will need and use, it wouldn't hurt to submit PRs.

**Comment by ddaniels888** [comment]
@ybroze same here—no immediate plans to use those, but if it's out in open source it'll probably get picked up by others!

**Comment by dlstadther** [comment]
@ybroze if it's a motivating factor, I do have a few tasks now that `create table as`. Presently, I'm bypassing Luigi structure and executing these commands with sqlalchemy. If you submit a PR for this functionality, i will definitely use it!

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
