### ISSUE TITLE
Memory leak when reading from huge gzipped S3Target

### ISSUE THREAD

**Issue by jpiper** [spotify/luigi#1467]
I have a 80GB `.csv.gz` file on S3 that I'm trying to use an in input, e.g.

`luigi.s3.S3Target(S3_PATH, format=luigi.format.Gzip)`

When I try to iterate through it during my Task's `run()` method, even when passing the data to nowhere, my memory gets eaten up completely!

```python
infile = self.input().open('r')
for i in infile:
     pass
```

I'm on boto 2.38.0 and luigi 2.0.1

**Comment by deuxpi** [comment]
I'm going to guess that line 79 of luigi/format.py is a major suspect because I don't expect boto to provide a `fileno()` attribute on the key. That reads the whole data in memory to be copied to a temporary file. A simple fix would be to read from the `input_pipe` by chunks, just like boto would do for us if it were a plain file.

**Comment by Tarrasch** [comment]
Wow, thanks @deuxpi !!

**Comment by jpiper** [comment]
Wow, talk about a fast turnaround! I just can't believe that I'm the person person to encounter this issue :)
