### ISSUE TITLE
no more tasks when requires_local done

### ISSUE THREAD

**Issue by nkbaob** [spotify/luigi#1470]
hi , I got a question about requires_local
I have two luigi.hadoop.JobTask for map-reduce job, but both two tasks should pull the same data first
as the document said, there is a instance cache for tasks, so I just give the same parameters in the two requires_local, it look like:

def requires_local(self):
   return [pull_data.PullData(client=self.client, d
                                   segment_id=self.segment_id,
                                   endpoint=self.endpoint,
                                   start_date=self.pull_start_date, 
                                   end_date=self.pull_end_date,
                                   conf_file=self.conf_file, 
                                   env=self.env)]

to ensure the pulling action not run twice, or the data should be duplecated. but when I run two tasks meanwhile, it seems not work, one of the tasks always finish directly after scheduled the pullData,  and said "There are no more tasks to run at this time", but the pullData is still in "PENDING" status, why that task didn't wait until the pull task done and run its mr job?

the log:  
2015-12-25 06:05:04       Scheduled PullData(client=seg1, segment_id=68, model_id=None,...)(PENDING)
2015-12-25 06:05:04     Running Worker with 1 processes
2015-12-25 06:05:04 luigi-interface INFO           Done
2015-12-25 06:05:04 luigi-interface INFO           There are no more tasks to run at this time
 2015-12-25 06:05:04 luigi-interface INFO           PullData(client=seg1, segment_id=68, ....) is currently run by worker Worker(salt=143519565, workers=1, host=hostname, username=hdfs, pid=2300)

**Comment by davemt** [comment]
I believe you need to enable the `worker-keep-alive` configuration boolean in order for the second worker to wait for the shared task run by the first worker to complete.

`worker-keep-alive`
If true, workers will stay alive when they run out of jobs to run, as long as they have some pending job waiting to be run. Defaults to false.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
