### ISSUE TITLE
RQ backend viable ?

### ISSUE THREAD

**Issue by ldng** [spotify/luigi#1481]
I was wondering if those who know enough Luigi's internals if an RQ backend would be viable.
We would love to have a simple batch workflow atop RQ and Luigi looks quite neat but Hadoop is way too overkill for our current needs.

**Comment by erikbern** [comment]
What's RQ?

**Comment by ldng** [comment]
Sorry, I forgot to put a link : http://python-rq.org/

> RQ (Redis Queue) is a simple Python library for queueing jobs and processing them in the
> background with workers. It is backed by Redis and it is designed to have a low barrier to entry.
> It can be integrated in your web stack easily.

**Comment by erikbern** [comment]
sure, would make sense

**Comment by Tarrasch** [comment]
I'm not sure I understand what you ask for. Are you asking if a RQ backend would viable as a replacement for something??

**Comment by stellasia** [comment]
Hi,
Looks like we have the same kind of issue: we have to run batch of jobs with complex dependencies that luigi seems to address very well. But the jobs are not well-suited for map-reduce and we would like to use RQ instead. Any chance that luigi can handle RQ jobs instead of hadoop ones?
I don't know enough of luigi to look at the code myself but if you have any indication on where to start, I can have a look.
Thanks!

**Comment by Tarrasch** [comment]
Luigi is really in no way tied to map-reduce. It has it's root there though and many of design decisions still today consider luigi as predominantly used in big data settings (few tasks, but usually big).

I don't know enough RQ to really understand where to point you. Sorry. :)

**Comment by erikbern** [comment]
all you need to do is subclass `luigi.Task` and implement a `run` method – should be easy :)

**Comment by davemt** [comment]
Comparing to M/R, luigi submits a single `luigi.Task` per hadoop job of course but that job has many parts parallelized. Are you trying to have a 1-to-1 with luigi task in the flow or would you expect to have many little RQ-task's for a given luigi task step?

**Comment by stellasia** [comment]
Thanks for the comments.

Subclassing `luigi.Task` and implementing `run` would make sense only if the run method itself wait for the rq job to end before returning, otherwise it would just enqueue the job and return, and job dependencies would be broken. But this could perhaps be a solution, I have to think more about it. 

> Are you trying to have a 1-to-1 with luigi task in the flow or would you expect to have many little RQ-task's for a given luigi task step?

1-to-1.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [x] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
