### ISSUE TITLE
RemoteTarget creates a non-existant file/directory, but its test expects a raised error

### ISSUE THREAD

**Issue by econchick** [spotify/luigi#1495]
Hey folks -

I was taking a look at some tests, when I saw that on Travis, one particular test that is testing `luigi/contrib/ssh.py` [fails but the build still succeeds](https://travis-ci.org/spotify/luigi/jobs/101167651#L308). I thought I'd fix this, since I assumed that creating a temp file in `/etc` was the issue by just using Python's `tempfile` lib.

However, digging through `luigi/contrib/ssh.py:RemoteTarget`, it looks like the creation of the `file_writer` creates the parents' directories automatically (and then for the actual file to be created if it's not already there). So that leads me to be a bit confused that the associated test [luigi/contrib/test_ssh.py](https://github.com/spotify/luigi/blob/master/test/contrib/test_ssh.py#L195-L200) expects `RemoteCalledProcessError` to be raised, when it's actually not.

Which would be the preferred behavior?

**Comment by Tarrasch** [comment]
Doing the `git blame` chase I found this #1246 PR by @demoray. Would be nice of someone using ssh could chime in.

**Comment by demoray** [comment]
Sorry for the delay, work beckoned.  Technically, the test does not fail.  There is quite a bit of work being done within \_\_del\_\_.  Python docs warn against [this](https://docs.python.org/2/reference/datamodel.html#object.__del__)

The PR that @Tarrasch linked was a preventative measure to protect against the infinite recursion that was occurring.

I have hoped to cleanup the InputPipe and OutputPipe wrappers when I had time, but given the recent desire to yank out all of the atomic file systems into its own project, perhaps this should be done then?

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [x] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
