### ISSUE TITLE
The number on visualiser web page is all 0

### ISSUE THREAD

**Issue by bob-zhao-work** [spotify/luigi#1516]
Hello,

I just installed the luigi on one Ubuntu PC and get the samples run successfully.
When I try to check the job history through luigid, the page can show up, but all the numbers are 0 and the list is empty also. Do I miss something there? 

Thanks,
Bob

**Comment by erikbern** [comment]
not sure why – maybe you used the local scheduler?

**Comment by leafjungle** [comment]
there is a configuration named "remove_delay", it can make the tasks shown longer.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
