### ISSUE TITLE
task always "running"

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1548]
hello guys. 
I encounter a case: a tasks is always running, but the corresponding worker is killed.
I have checked the "worker-disconnect-delay". It should be marked as failed or pending as the worker is killed after that time.  But I do not know why it is always in "running" status.

**Comment by leafjungle** [comment]
This is related with "def prune" in "class SimpleTaskState".
When a running task with no stakeholders or running_workers, it will not set as failed, but just remove it after "remove_delay" times.  And during this time, all its resources will not be released, which is not suitable at all.

------------------------here is the code of luigi 1.2.1
    def prune(self, task, config, assistants):
        remove = False

        # Mark tasks with no remaining active stakeholders for deletion
        if not task.stakeholders:
            if task.remove is None:
                logger.info("Task %r has stakeholders %r but none remain connected -> will remove "
                            "task in %s seconds", task.id, task.stakeholders, config.remove_delay)
                task.remove = time.time() + config.remove_delay

        # If a running worker disconnects, tag all its jobs as FAILED and subject it to the same retry logic
        if task.status == RUNNING and task.worker_running and task.worker_running not in task.stakeholders | assistants:
            logger.info("Task %r is marked as running by disconnected worker %r -> marking as "
                        "FAILED with retry delay of %rs", task.id, task.worker_running,
                        config.retry_delay)
            task.worker_running = None
            self.set_status(task, FAILED, config)
            task.retry = time.time() + config.retry_delay
------------------------

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
