### ISSUE TITLE
About the "task statistics"

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1553]
As we know each task has some statistics info, such as how much data it processed, how long does it last, how much data is processed successfully/fail/exception.

I think each Task should have a dict member called "stat_info", we can add any elements in it. And it can be displayed in the webpage.

That is really awesome if Luigi have that thing.

**Comment by Tarrasch** [comment]
Yea I like to see something like this too. We just need to ensure however we implement it we do it in a clean way. It's easy to do it to general or too specific.

**Comment by hangelwen** [comment]
+1. This will be very useful.

**Comment by erikbern** [comment]
yes i like this too

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
