### ISSUE TITLE
CopyToPostgres inserts data twice because of updated update_id

### ISSUE THREAD

**Issue by oldpa** [spotify/luigi#1578]
Related to: https://github.com/spotify/luigi/pull/1444

When I updated to latest version of luigi it started to reimport old data because of changes in how we calculate update_id/task_id.

I created a migration script for migrating from old task_id to new task_id.

```
# migrate_update_id.py
import sys
import re
import luigi.task
def create_marker_row(line):
    task_id, table_name = map(lambda x: x.strip(), line.split('|'))
    task_class, args = re.match('(.*)\((.*)\)', task_id).groups()
    d = {}
    for arg in args.split(','):
        key, value = arg.strip().split('=')
        d[key] = value
    task_id = luigi.task.task_id_str(task_class, d)
    print "insert into table_updates (update_id, target_table) values ('%s', '%s');" %( task_id, table_name)
for line in sys.stdin:
    create_marker_row(line)
```

```
# Run this command, first gets all marker_tables from postgres, create insert queries for
# new marker tables and then inserts back to postgres
sudo -u postgres psql pipeline -t -c 'select update_id, target_table from table_updates' | python migrate_update_id.py | sudo -u postgres psql pipeline
```

**Comment by erikbern** [comment]
we probably should have made it backwards compatible :(

**Comment by akaul** [comment]
@erikbern @oldpa Is there any interest in making `RedshiftTarget` backwards compatible? I was able to successfully patch to maintain backwards compatibility while migrating from a lower Luigi version to version 2.1.1.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
