### ISSUE TITLE
Design: serialization of none parameters

### ISSUE THREAD

**Issue by ihat** [spotify/luigi#1591]
Currently, luigi.Parameters with value `None` is serialized as `'None'` since `str(None) == 'None'`.

This could lead to issues when adding tasks remotely, since the remote worker would interpret a None parameter as 'None'.

Should we serialize None parameters differently, perhaps in `to_str_params` and `from_str_params`?

**Comment by ihat** [comment]
Related issue: https://github.com/spotify/luigi/issues/1100

**Comment by Tarrasch** [comment]
Yea. I haven't had the resources/time to once and for all fix this. I would phrase it that luigi currently doesn't support `None` as a value to parameters, if you still use it the behaviour is undefined.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [x] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
