### ISSUE TITLE
Range is sensitive to trailing slash

### ISSUE THREAD

**Issue by ulzha** [spotify/luigi#1599]
E.g. RangeHourly of a task whose output FileSystemTarget's path ends in '%Y-%m-%d/%H/' fails to interpret listing as containing existing partitions correctly. Using '%Y-%m-%d/%H' works around it.

**Comment by Tarrasch** [comment]
Yea there's been some spooky bug in Range-non-Base which have affected both me and others. Will you be able to fix it? :)

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
