### ISSUE TITLE
job control

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1605]
hi, guys：
      I have a job, which contains 3 tasks.
      (1)how can I trigger the job, making it run every 20 minutes, without using crontab?
      (2)When the previous job is not finished yet, the next job should wait.
           For example, in 18:02 pm, the job is triggered; and in 18:22, the job is triggered again, but it found that the 18:02's job is not finished yet, then the 18:22's job should wait.

```
   Is the luigi has that mechanism?
```

**Comment by Tarrasch** [comment]
> how can I trigger the job, making it run every 20 minutes, without using crontab?

There's no good replacement right now. However, you might find what you want in interface.py

> When the previous job is not finished yet, the next job should wait.

Why do you want that? Then a lot of processes would just pile up and take down your system. No? Or do you mean for different workflows having the same dependency? If so. Search for the "worker keep alive" options in the docs.

Good luck.

**Comment by erikbern** [comment]
For (2) you should just have a dependency so that the second job requires the first job

**Comment by leafjungle** [comment]
@Tarrasch .  Because there are other limitations. Consider this situation: A lot of tasks are running on hadoop cluster or on a machine, they take a lot of resources. And another situation: the later data should not be processed before the earlier data, so they can not be processed at the same time.

**Comment by erikbern** [comment]
> And another situation: the later data should not be processed before the earlier data, so they can not be processed at the same time.

in this case you should just have a dependency using `requires` – why not

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
