### ISSUE TITLE
Wrong partition name leads to erroneous  task finish status

### ISSUE THREAD

**Issue by junchenfeng** [spotify/luigi#1668]
The output should be 
`HivePartitionTarget(table='a',database='b',partition={subject':'english','end_dt':'2016-04-22'})`

Instead I wrote 
`HivePartitionTarget(table='a',database='b',partition={subject':'english','dt':'2016-04-22'})`

Where partition name end_dt is replaced with dt. 

Luigi report the task is done although the partition target is NOT there

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
