### ISSUE TITLE
Generic database target

### ISSUE THREAD

**Issue by dylanjbarth** [spotify/luigi#1684]
In some of our pipelines, we have long running tasks which don't have clear output. For example, a task which reads in data from multiple tables in one schema, and updates (rather than inserts) into a single table in another schema. As for as I can tell, this isn't the use case for something like the `sqla.CopyToTable` task. 

My workaround was a slightly more generic version of the `mysqldb.MySqlTarget` where we omit the update table column and simply keep a record of every successful task run, using `task_id` as the update ID. 
1. Is there a better pattern for cases like this that I have missed? 
2. If not, I'd be happy to submit a PR after cleaning it up a bit.

**Comment by dylanjbarth** [comment]
Potentially similar to https://github.com/spotify/luigi/issues/1149

**Comment by alexshires** [comment]
I'd definitely be interested in this - but for elasticsearch as well as sqla.

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
