### ISSUE TITLE
about mysql or redis

### ISSUE THREAD

**Issue by levylll** [spotify/luigi#1697]
Excuse me, would you give me an example for redis or mysql?

**Comment by levylll** [comment]
Btw, I'd like to know how to write data into my redis.
Thank you very much.

**Comment by dlstadther** [comment]
I don't use the redis or mysql modules, but I can provide an [example](https://gist.github.com/dlstadther/f835a234f54a46728412) for Redshift.

**Comment by levylll** [comment]
@dlstadther Thank you very much. After reading your example and the src in contrib, I think I have to add some function for redis_store....

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [X] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
