### ISSUE TITLE
Rerun task with same parameters without removing outputs

### ISSUE THREAD

**Issue by jkryanchou** [spotify/luigi#1725]
Hi folks,

```
 Recently, an requirement did trouble me a lot. I need to update the latest data file with `_latest.txt` suffix while I didn't want to generate the latest file with timestamp. So I couldn't rerun the task with same parameters. I have tried some methods on it, While It seems didn't work.
```

```
import luigi
import uuid

class FooTask(luigi.Task):

     foo = luigi.Parameter()

      def __init__(self, *args, **kwargs):
           self._dont_filter = uuid.uuid1().hex
           super(FooTask, self).__init__(*args, **kwargs)

a = FooTask(foo="foo")
b = FooTask(foo="foo")

print(a is b)
```

Output:

```
False
```

And it showed me that python internal mechanism processed the Class object initialization with same parameters without init method executions more than once. So I wonder luigi core developers could provide a flag parameter like `dont_filter` in `luigi.Task` could make us task rerun the task above in multiple times? Or offer me a better solution instead of removing outputs.

**Comment by mfcabrera** [comment]
I think this is a related of #595. 

 I am closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [x] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
