### ISSUE TITLE
Luigi doesnt show help with --help

### ISSUE THREAD

**Issue by alfonsomhc** [spotify/luigi#1727]
In the command line, I have problems printing help:
$ luigi --help
Traceback (most recent call last):
  File "/home/alfonso/anaconda2/bin/luigi", line 6, in <module>
    sys.exit(luigi.cmdline.luigi_run())
  File "/home/alfonso/anaconda2/lib/python2.7/site-packages/luigi/cmdline.py", line 13, in luigi_run
    luigi.interface.run(argv, use_dynamic_argparse=True)
  File "/home/alfonso/anaconda2/lib/python2.7/site-packages/luigi/interface.py", line 421, in run
    tasks = interface.parse(cmdline_args, main_task_cls=main_task_cls)
  File "/home/alfonso/anaconda2/lib/python2.7/site-packages/luigi/interface.py", line 329, in parse
    **import**(module)

This works fine though (help is printed):
$ luigi -h

**Comment by Tarrasch** [comment]
This is a really undesirable bug. We have test cases for exactly this, not sure why it isn't tested in an environment like yours. :-/

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [x] Cannot reprodue


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
