### ISSUE TITLE
If a worker times out and the task is marked as "FAILED", the history still shows it as "RUNNING"

### ISSUE THREAD

**Issue by rocketmonkeys** [spotify/luigi#1739]
Steps:
- Start a task via command line that will take a while
- Wait a few seconds (so it registers with the scheduler), then kill the task (control+C)
- Wait 60 seconds
- Go to the scheduler UI/API - the task shows as "FAILED", and the logs show "INFO: Worker Worker(...) timed out (no contact for >=60.0s)"
- HOWEVER - if you go to /history, the status shows as "RUNNING" and is never updated
- Even if you restart luigid, the task will forever show as RUNNING in /history

Looks like the history feature is not properly being updated, even though the UI is.

(EDIT: luigi 2.1.1)

**Comment by sbourke** [comment]
Can you share some code to replicate the problem ?

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
