### ISSUE TITLE
Time column is not sorted correctly in the UI

### ISSUE THREAD

**Issue by alexrovner** [spotify/luigi#1807]
Version 2.2.0

When you click on "Time" it sorts the date / time using string sort instead of date / time sort resulting in incorrect results. Example of the sorted values:
8/5/2016, 12:30:16 AM
8/5/2016, 12:30:31 PM
8/5/2016, 1:30:09 AM  
8/5/2016, 1:30:27 PM

<img width="788" alt="screen shot 2016-08-05 at 4 03 43 pm" src="https://cloud.githubusercontent.com/assets/597453/17449098/3f4ae964-5b26-11e6-9225-cda50eb99930.png">

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
