### ISSUE TITLE
Having custom task_family for dynamic dependencies

### ISSUE THREAD

**Issue by javrasya** [spotify/luigi#1812]
I have some generic tasks which can be parameterised. Beucase, they are same class, luigi ui shows them as same name as class name. I changed each instance task_family to show them with different names even the class is common. This works properly for normal dependencies. I realised that, this is not working for dynamic dependencies. Here is the error raised by luigi;

``` console
TaskClassNotFoundException: No task MyTaskWithCustomTaskFamily. Candidates are: .....
```

I looked into luigi code and I found somewhere which registers the new_deps with its task_family instead of registering it with class name.

`in worker.py -> _run_get_new_deps()`

``` python
...
 new_deps = [(t.task_module, t.task_family, t.to_str_params())
                            for t in new_req]
...
```

this should be something like;

``` python
...
 new_deps = [(t.task_module, t.__class__.__name__, t.to_str_params())
                            for t in new_req]
...
```

Here, I created a case for it;

``` python
from helpers import LuigiTestCase
from luigi import Task
from luigi.scheduler import Scheduler
from luigi.worker import Worker

_author_ = 'ahmetdal'


class DummyTask(Task):
    def __init__(self, *args, **kwargs):
        super(DummyTask, self).__init__(*args, **kwargs)
        self.has_run = False

    def complete(self):
        return self.has_run

    def run(self):
        self.has_run = True


class HavingCustomTaskFamilyCase(LuigiTestCase):
    def setUp(self):
        super(HavingCustomTaskFamilyCase, self).setUp()
        self.sch = Scheduler()

    def test_for_normal_dependencies(self):
        class B(DummyTask):
            task_family = 'custom_B'

        b = B()

        class A(DummyTask):
            def requires(self):
                return b

        a = A()

        with Worker(scheduler=self.sch) as w:
            self.assertTrue(w.add(a))
            self.assertTrue(w.run())

    def test_for_dynamic_dependencies(self):
        class B(DummyTask):
            task_family = 'custom_B'

        b = B()

        class A(DummyTask):
            def run(self):
                yield b
                super(A, self).run()

        a = A()

        with Worker(scheduler=self.sch) as w:
            self.assertTrue(w.add(a))
            self.assertTrue(w.run())
```

Execution output is;

``` console
TaskClassNotFoundException: No task custom_B. Candidates are: A,B,Config,DummyTask,ExternalTask,RangeBase,RangeDaily,RangeDailyBase,RangeHourly,RangeHourlyBase,RunOnceTask,Task,TestNotificationsTask,WrapperTask,core,execution_summary,scheduler,worker

```

If this seems as a bug, I can create PR for it.

**Comment by Tarrasch** [comment]
Actually, I'm not sure if it should be allowed to set `task_family`. Does it still crash if you only set `task_namespace`?

**Comment by javrasya** [comment]
We are using to override `task_family` to change task name on luigi gui. This is really useful to have different names. Actually it works like a charm for normal dependencies. Luigi does make no trouble about it. I thought that, the behaviour should be same for dynamic dependencies too.

There is no crash for `task_namespace`, but it doesn't help to change task name.

**Comment by drj42** [comment]
I use task namespaces extensively in my projects as a means of task organization, and this issue made me question my assumptions about them (but I think it turns out they were on point).
 
@javrasya If I'm understanding you correctly, it sounds like task namespaces are really what you want to be using instead.  When a  `task_namespace` is given a value, its incorporated into `task_family` value (prefixed to `task_name`), .e.g.

```
class Foo(luigi.Task):
    task_namespace = 'custom_a'
```

Foo's `task_family` is now: `custom_a.Foo`, and as far as the scheduler is concerned, is a different from any `Foo` task class that may defined in other modules or scopes and task namespaces.  It groups them like you'd expect in the scheduler view.

If I recall though, the scheduler *used* to group the tasks up by task class name only, and didn't look at the namespace, in the sidebar view.  At some point this changed.  If at some point you tried this same technique with namespaces and it didn't work like you were hoping, try updating luigi (scheduler and workers) and see if that helps.

(see https://github.com/spotify/luigi/blob/master/luigi/task_register.py#L121)
