### ISSUE TITLE
LocalTarget.exists no-permission fails silently and returns False

### ISSUE THREAD

**Issue by freider** [spotify/luigi#192]
The exists check should probably raise an exception if it doesn't have permission to see if the file exist.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
