### ISSUE TITLE
sqla how to set schema of table

### ISSUE THREAD

**Issue by rhaarm** [spotify/luigi#1939]
How to define the schema of {schema}.{table} in luigi.contrib.sqla.CopyToTable? Do I need to update the class to allow custom metadata class or \_\_table_args\_\_?

**Comment by rhaarm** [comment]
I've made changes to add ```self.metadata = sa.MetaData()```, but this will need some testing, any other thoughts on this would be appreciated.

**Comment by stickystyle** [comment]
Are you asking about the table and column definitions?

Here's an example of a table definition using sqla.CopyToTable from my own usage.
```python
class LoadInspectionKPI(CopyToTable):
    columns = [
        (["Inspection_Date", Date()], {}),
        (["Inspection_Person", String(120)], {}),
        (["Vendor", String(250)], {}),
        (["Carton_ID", Integer()], {}),
        (["Serial_Number_Count", Integer()], {})
    ]
    table = 'inspection_kpi'
```

If you actually want work right with the MetaData you can bind it like this...
(snip from on of my classes that override `run()` in CopyToTable
```python
output = self.output()
engine = output.engine
meta = MetaData()
meta.reflect(bind=engine)
```

**Comment by rhaarm** [comment]
When I refer to schema I'm referring to a database schema {database}.{schema}.{table}, not the table definition.

Like when using MetaData(schema='schema_name'), which is why I opted to change the class to allow for custom MetaData class versus redefining the run() for every CopyToTable Task.

**Comment by buyology** [comment]
Much needed indeed!

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
