### ISSUE TITLE
Worker and Scheduler notifications

### ISSUE THREAD

**Issue by jnthm** [spotify/luigi#1940]
Hi, 
We have been using luigi at Ooyala at a large scale to run thousands of jobs daily. 
We would not like to alert via email for every worker task failure -- only if there are certain number of failures.

After every failure, worker sends an email based on the email configuration settings provided in the luigi.cfg. 
However, scheduler sends an email ONLY after maxing out all the failure attempts.

So, we would like to receive email notifications from scheduler, but not from the worker. Since they read the email configurations from the same section in luigi.cfg, it doesn't look like we can achieve this unless we run scheduler and workers on different machines (where we can configure email for scheduler but not for workers).

**So, here we propose the capability of separate scheduler and worker email settings in luigi.cfg.**

Please let me know if this can already be achieved without the above proposal.

**Comment by Tarrasch** [comment]
A recent PR greatly improved email capability of luigi. What do you think of #1916?

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
