### ISSUE TITLE
Binary or Gzip Write S3Target

### ISSUE THREAD

**Issue by rhaarm** [spotify/luigi#1983]
Does anyone have an examples of writing Binary target for S3Target? I've tried multiple things to get this to work the way I want it too, but it doesn't seem to support binary open no matter. I've implemented the way of writing the Gzip file as a separate task, but I want that file to be temporary, so using requires has an affect before pushing to S3 can cause dependency error down the road. The temp=True flag doesn't seem to work correctly either, since the file gets deleted before being pushed to S3.

Thoughts?

**Comment by jtratner** [comment]
Have you tried passing `format=luigi.formats.GzipFormat()` to the S3Target constructor?  That'll make it automatically gzip it (by passing it through the local `gzip` command.  The `S3File` object just needs a few more methods to be passed to, e.g., `GzipFile` normally.

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [x] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
