### ISSUE TITLE
RangeDaily with luigi.WrapperTask

### ISSUE THREAD

**Issue by slarrain** [spotify/luigi#2005]
Hi,

First of all, I wanted to thank everyone involved on luigi. Is an awesome library.

At the moment, I have a Wrapper Task that looks like this:
```
class runAll(luigi.WrapperTask):
    """
    Wrapper Task class that runs the pipeline once for each query or table.
    """
    date = luigi.DateParameter(default=datetime.date.today() - datetime.timedelta(days=1))
    def requires(self):
        yield loadToPostgres(date=self.date, qtable='session')
        yield loadToPostgres(date=self.date, qtable='session_features')
        yield loadToPostgres(date=self.date, qtable='events')
        yield loadToPostgres(date=self.date, qtable='client')
```

And it works fine with:
`luigi.run(['runAll', '--date', '2017-01-02', '--local-scheduler'])`
Or whatever date I specified.

However, if I try to add a `RangeDaily`, it fails:

```
luigi.run(['RangeDaily', '--of', 'runAll', '--start', '2017-01-02', '--stop', '2017-01-07', '--local-scheduler'])

$ python3 gaETL.py 
/usr/local/lib/python3.5/dist-packages/luigi/parameter.py:259: UserWarning: Parameter None is not of type string.
  warnings.warn("Parameter {0} is not of type string.".format(str(x)))
DEBUG: Checking if RangeDaily(of=runAll, of_params={}, reverse=False, task_limit=50, now=None, param_name=None, start=2017-01-02, stop=2017-01-07, days_back=100, days_forward=0) is complete
DEBUG: Actually checking if range [2017-01-02, 2017-01-06] of runAll is complete

WARNING: Will not run RangeDaily(of=runAll, of_params={}, reverse=False, task_limit=50, now=None, param_name=None, start=2017-01-02, stop=2017-01-07, days_back=100, days_forward=0) or any dependencies due to error in complete() method:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/tools/range.py", line 663, in missing_datetimes
    complete_parameters = self.of.bulk_complete.__func__(cls_with_params, map(self.datetime_to_parameter, finite_datetimes))
  File "/usr/local/lib/python3.5/dist-packages/luigi/task.py", line 500, in bulk_complete
    raise BulkCompleteNotImplementedError()
luigi.task.BulkCompleteNotImplementedError
```

This probably has something to do with this: 

> It has the same knobs as RangeDailyBase, with some added requirements. Namely the task must implement an efficient bulk_complete method, or must be writing output to file system Target with date parameter value consistently represented in the file path.
(http://luigi.readthedocs.io/en/stable/luigi_patterns.html#efficiently-triggering-recurring-tasks)

So I guess my questions is: How can I solve this problem? How can I use a WrapperTask with RangeDaily? How can I implement an efficient bulk_complete method? (My `loadToPostgres` class inherits from a `luigi.postgres.CopyToTable` class)

Thanks!

Santiago.

**Comment by Tarrasch** [comment]
Good questions. I think you could either use the `RangeDailyBase` or let your task inherit from [this mixin](http://luigi.readthedocs.io/en/stable/api/luigi.task.html#luigi.task.MixinNaiveBulkComplete). I see this is not really clear from the docs, perhaps you want to contribute back with some docs? :)

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
