### ISSUE TITLE
Luigi Visulizer Stuck

### ISSUE THREAD

**Issue by steveb-cirina** [spotify/luigi#2008]
Hi

I am having an issue with the Luigi Visulizer web page getting stuck as shown in the image below:

![luigi_visualizer_webpage_stuck](https://cloud.githubusercontent.com/assets/22382505/22449091/de56ef80-e712-11e6-8edd-d93014af5915.png)

I am running on Mac OS X 10.11.6 (El Cap.) using Python 2.7.12 and Luigi 2.3.0.

I stopped "luigid" and restarted it but that does not fix the issue.  I have rebooted my machine and restarted but the issue continues.

Is there some file somewhere that I have to clean up ?

**EDIT**

The URL I am using is "http://localhost:8082/"

Also, this did initially work when I first installed it.

Thanks.

**Comment by Tarrasch** [comment]
Actually. I have this issue for some reason too. It happens for me when the scheduler isn't running at all, because I think the browser remembers "luigi webui" in the cache or something. It's not re-downloading the frontend stuff on a page refresh. But whenever I restart the scheduler data starts to get populated again.

**Comment by steveb-cirina** [comment]
Unfortunately restarting the scheduler didn't work for me (for Chrome).  I restarted my laptop (where the scheduler was running) and that didn't fix it either.  However, I just launched "luigid" and tried it in Safari and it is NOT having the same problem.  I think you might be right about the browser caching.

**Comment by steveb-cirina** [comment]
I just "fixed" the issue in Chrom.  Instead of reloading with "Command-R" I did "Command-shift-R". That should NOT have fixed it as Command-shift-R is the short cut for "Show Reader", so I am not sure why this is working now.

Thanks for your comments.

**Comment by steveb-cirina** [comment]
Is this something that can be handled ("fixed"?) in the web interface ?

**Comment by Tarrasch** [comment]
@steveb-cirina, probably there's some setting somewhere telling the browser how long to cache stuff. But actually I have no idea, I know very little about web development. If you look into this and find a fix, please send a PR. :)

**Comment by steveb-cirina** [comment]
Thanks for the info about Firefox producing this issue consistently.  I am new to luigi so I don't know how often this issue occurs or what will cause it to occur.  I will see if I can find a potential fix when it occurs again.

**Comment by colspan** [comment]
I had this issue too. I recommend to check your browser decoding setting when this happens.
In my case, the browser(Chrome, Firefox) fails to parse URI.js(at line 216 on v2.6.0), because of wrong detection (was Shift-JIS for me) for decoding luigi visualizer's files. Setting 'UTF-8' manually helps to fix this issue.

I guess the fundamental solution is to put `<meta charset="utf-8">` on `luigi/static/visualiser/index.html`.
Thank you:)

**Comment by steveb-cirina** [comment]
@colspan Thanks for digging into this!  I haven't seen this issue since the day I posted this.

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
