### ISSUE TITLE
Scheduler colors are bad for colorblindness 

### ISSUE THREAD

**Issue by JoeEnnever** [spotify/luigi#201]
It's hard to tell the difference between pending, failed, and complete tasks, especially with a bunch of them on top of each other.

With deuteranopia (common):
![screen shot 2013-10-10 at 7 02 43 pm](https://f.cloud.github.com/assets/410962/1311123/9e1b1aba-3200-11e3-9cf6-4fbf9b7e75c3.png)

and protanopia (rarer):
![screen shot 2013-10-10 at 7 02 53 pm](https://f.cloud.github.com/assets/410962/1311140/cb230658-3200-11e3-8929-1a5b0975a4dd.png)

Maybe add check marks to done, dashes to pending, and x's to failed?

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Comment by Tarrasch** [comment]
I marked this as "big change" because I suspect one would need to add skins you can choose from. Can any one set of color work for all types of being color blind? 

I would be really happy to also accept a small change that fixes this (changes the colors), given that the new color palette looks "better" for users with full color vision as well.
