### ISSUE TITLE
Trying to implement dynamic building of task dependencies from config results in the scheduler not running the tasks

### ISSUE THREAD

**Issue by Kaleidophon** [spotify/luigi#2052]
Hi!

I also posted this issue on [Stackoverflow](http://stackoverflow.com/questions/42563175/how-to-enable-dynamic-requirements-in-luigi). I will just copy-paste it for now, I hope the description of my problem is descriptive enough.

-----------------

I have built a pipeline of Tasks in Luigi. Because this pipeline is going to be used in different contexts, it was possible that it would require to include more tasks at the beginning of or the end of the pipeline or even totally different dependencies between the tasks.

That's when I thought: "Hey, why declare the dependencies between the tasks in my config file?", so I added something like this to my `config.py`:

    PIPELINE_DEPENDENCIES = {
         "TaskA": [],
         "TaskB": ["TaskA"],
         "TaskC": ["TaskA"],
         "TaskD": ["TaskB", "TaskC"]
    }
I was annoyed by having those stacking up parameters throughout the tasks, so at some point I introduced just one parameter, `task_config`, that every `Task` has and where every information or data that's necessary for run() is stored. So I put `PIPELINE_DEPENDENCIES` right in there.

Finally, I would have every `Task` I defined inherit from both `luigi.Task` and a custom Mixin class, that would implement the dynamic requires(), which looks something like this:

    class TaskRequirementsFromConfigMixin(object):
        task_config = luigi.DictParameter()

        def requires(self):
             required_tasks = self.task_config["PIPELINE_DEPENDENCIES"]
             requirements = [
                 self._get_task_cls_from_str(required_task)(task_config=self.task_config)
                 for required_task in required_tasks
             ]
            return requirements

        def _get_task_cls_from_str(self, cls_str):
             ...
Unfortunately, that doesn't work, as running the pipeline gives me the following:

     ===== Luigi Execution Summary =====

     Scheduled 4 tasks of which:
     * 4 were left pending, among these:
         * 4 was not granted run permission by the scheduler:
             - 1 TaskA(...)
             - 1 TaskB(...)
             - 1 TaskC(...)
             - 1 TaskD(...)

    Did not run any tasks
    This progress looks :| because there were tasks that were not granted run permission by the scheduler

     ===== Luigi Execution Summary =====
and a lot of

     DEBUG: Not all parameter values are hashable so instance isn't coming from the cache
Although I am not sure if that's relevant.

So: 1. What's my mistake? Is it fixable? 2. Is there another way to achieve this?

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [x] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
