### ISSUE TITLE
util.inherits and requires use inheritence, breaking the MRO

### ISSUE THREAD

**Issue by sbliven** [spotify/luigi#2054]
As discussed in on [the mailing list](https://groups.google.com/forum/#!topic/luigi-user/7m0uZkyyYow), using @inherits messes up the method resolution order and breaks `super()`

```
>>> class Foo(luigi.Task): pass
...
>>> @inherits(Foo)
... class Bar(luigi.Task): pass
...
>>> Bar.__mro__
(<class '__main__.Bar'>, <class '__main__.Bar'>, <class 'luigi.task.Task'>, <type 'object'>)
```

Since Bar is now twice on the list, any calls to super will result in infinite loops.

This problem comes from @inherits using inheritance to modify the class. We should look into whether the class can be monkey-patched instead of subclassed, so that inheritance works as expected.

**Comment by DavidS3141** [comment]
Just ran into this issue. Using super() in python 3 works though, but I wanted to use the python 2 super(class, self) which results in the infinite loops (for compatibility reasons).
In the task i need to cache a input() since the loading of the file format takes forever. Wanted to do this in the __init__ of the task, and here I need the super() call for the arguments. Is this gonna be fixed soon (or a fix even possible), or a workaround for my (pretty generic) case? Something like a init() function of the base class luigi.Task which I could overwrite perhaps?

**Comment by Tarrasch** [comment]
@DavidS3141, I don't think anyone is currently working on this. Could you take a try yourself?

**Comment by DavidS3141** [comment]
@Tarrasch this is my try ;) but i am a total newbie in pull requests actually ;) Hope this looks fine to you!
