### ISSUE TITLE
Failed dependency reported only once

### ISSUE THREAD

**Issue by sisidra** [spotify/luigi#213]
Failed dependency is reported only once even if it was for different parent job.

``` python
class TestDepFail(luigi.ExternalTask):
    def complete(self): return False
class TestJob(luigi.Task):
    param = luigi.IntParameter()
    def complete(self): return False
    def requires(self): return TestDepFail()
class TestWrapJob(luigi.WrapperTask):
    def requires(self): return [TestJob(11111), TestJob(22222)]
```

output is:

> DEBUG: Checking if TestWrapJob() is complete
> INFO: Scheduled TestWrapJob()
> DEBUG: Checking if TestJob(param=22222) is complete
> INFO: Scheduled TestJob(param=22222)
> DEBUG: Checking if TestDepFail() is complete
> WARNING: Task TestDepFail() is not complete and run() is not implemented. Probably a missing external dependency.
> DEBUG: Checking if TestJob(param=11111) is complete
> INFO: Scheduled TestJob(param=11111)
> INFO: Done scheduling tasks

In my case it was 4 wrapped tasks each had 90+ dependencies with one failing. Just by looking at msgs for last wrapped job it is impossible to identify problem for that job.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
