### ISSUE TITLE
BaseHadoopJobTask always turns off reducers for hadoop jar tasks

### ISSUE THREAD

**Issue by JoeEnnever** [spotify/luigi#216]
`BaseHadoopJobTask.jobconfs` sets "mapred.reduce.tasks=0" if `reducer == NotImplemented`. Subclasses of `HadoopJarJobTask` would usually never override `reducer`, since the reducer is defined in the jar that it executes.

A hacky fix for this would be to set `reducer = None` in `HadoopJarJobTask`. Probably better would be to split up `BaseHadoopJobTask`, with one class providing generic jobconfs and the like, and `PythonHadoopJobTask` and a `JavaHadoopJobTask` classes that extend it.

Thoughts?

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
