### ISSUE TITLE
Significant parameters shown in GUI.

### ISSUE THREAD

**Issue by hirolau** [spotify/luigi#2164]
The docs state: "An insignificant Parameter might also be used to specify a password or other sensitive information that should not be made public via the scheduler"

However, given this code:

```
class Test(luigi.Task):
    user = luigi.Parameter(significant=True)
    password = luigi.Parameter(significant=False)

    def complete(self):
      return False
    def run(self):
      pass

if __name__ == '__main__':
    luigi.run(['Test','--user','myself','--password','123456'])
```

In the GUI when looking at the task I see: "user=myself, password=123456". The password is not hidden.

```
B:\luigi\code>pip show luigi
Name: luigi
Version: 2.6.2
```

**Comment by dckc** [comment]
FWIW: I worked around this by moving the password to an environment variable and using the parameter to name the environment variable.

**Comment by aldanor** [comment]
I'm also wondering about this. Could insignificant parameters be hidden from the GUI?

**Comment by langelgjm** [comment]
Title should be "**In**significant parameters shown in GUI"

I think the culprit is that in several places, the [Task.to_str_params()]( https://github.com/spotify/luigi/blob/50838d0aec0a13d48749fe63be069241dbaed085/luigi/task.py#L472) method is called with the default only_significant=False argument.

E.g., in [notifications.py](https://github.com/spotify/luigi/blob/50838d0aec0a13d48749fe63be069241dbaed085/luigi/notifications.py#L409), an e-mail body is created that would include insignificant parameters in plain text.

Contrast this with [deps_tree.py](https://github.com/spotify/luigi/blob/50838d0aec0a13d48749fe63be069241dbaed085/luigi/tools/deps_tree.py#L51) which excludes insignificant parameters.

Anything that is going to be displayed for visualization/notification should exclude insignificant / only include significant parameters.

**Comment by rhaarm** [comment]
Is someone working on a PR for this?

**Comment by edsonduarte1990** [comment]
This still happens, any news?

**Comment by dlstadther** [comment]
@edsonduarte1990 There have been many differing opinions around this (and the similar). For the open PR i'm aware of, see https://github.com/spotify/luigi/pull/2278

**Comment by dlstadther** [comment]
Closing, given the merge of #2278
