### ISSUE TITLE
Return non-zero exit code on task failure

### ISSUE THREAD

**Issue by bbakersmith** [spotify/luigi#2311]
Is there a way to get the luigi CLI to return non-zero exit codes on task failures? It seems by default it only prints the task status in human readable form to stderr. We would like our scripts to know if the tasks succeeded, but luigi returns 0 even if tasks have failed.

To work around this we have created a wrapper script as follows:

```bash
# get the luigi results from stderr
results="$(luigi "${@:1}" 2>&1)"

# print the results for debugging
echo "$results"

# grep the results to return a proper exit code
echo "$results" | grep 'This progress looks :)'
```

Is there a better way? Or would you be open to a PR to add this functionality?

**Comment by henryrizzi** [comment]
https://luigi.readthedocs.io/en/stable/configuration.html#retcode I think this might help you out

**Comment by bbakersmith** [comment]
Aha, this does seem like what I'm looking for. Thanks!

**Comment by GuilhermeSpadaccia** [comment]
Sorry to reopen this issue, but @henryrizzi suggestion doesn't work for me.
I don't know if I miss understood the feature, but even adding the section [retcode] to my luigi.cfg, if I do:
`python pypeline.py task --workers 4
echo $?`
The echo always returns 0 even when the task fails. Shouldn't it return the error described in [retcode] section on luigi.cfg?

**Comment by nesat** [comment]
I was facing this problem even with `[retcode]` [section](https://luigi.readthedocs.io/en/stable/configuration.html#retcode) in my `luigi.cfg` file. I have just found out the reason was using [`luigi.run()`](https://luigi.readthedocs.io/en/stable/running_luigi.html#response-of-luigi-build-luigi-run) instead of [`luigi` command line tool](https://luigi.readthedocs.io/en/stable/running_luigi.html#running-from-the-command-line). I think return codes don't work with `luigi.run()` for some reason. You can try:
```
export PYTHONPATH=$PYTHONPATH:~
luigi pypeline task --workers 4
echo $?
```
