### ISSUE TITLE
luigi.contrib.hdfs.HdfsTarget Not working.

### ISSUE THREAD

**Issue by Nikhillosalka** [spotify/luigi#2314]
I am trying to run below piece of code:

import luigi

class PrintNumbers(luigi.Task):
 
    def requires(self):
        return []
 
    def output(self):
        return luigi.LocalTarget("numbers_up_to_10000.txt")
 
    def run(self):
        with self.output().open('w') as f:
            for i in range(1, 11):
                f.write("{}\n".format(i))
 
class SquaredNumbers(luigi.Task):
 
    def requires(self):
        return [PrintNumbers()]
 
    def output(self):
        return luigi.contrib.hdfs.HdfsTarget('/log.txt')
 
    def run(self):
        print("Output")
                 
if __name__ == '__main__':
    luigi.run()

**Command** : python run_luigi.py SquaredNumbers  --local-scheduler
Expectation : Should create one local file. And one in HDFS.

Error: 
DEBUG: Checking if SquaredNumbers() is complete
WARNING: Will not run SquaredNumbers() or any dependencies due to error in complete() method:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/luigi/worker.py", line 334, in check_complete
    is_complete = task.complete()
  File "/Library/Python/2.7/site-packages/luigi/task.py", line 540, in complete
    outputs = flatten(self.output())
  File "run_luigi.py", line 22, in output
    return luigi.contrib.hdfs.HdfsTarget('/log.txt')
AttributeError: 'module' object has no attribute 'contrib'

INFO: Informed scheduler that task   SquaredNumbers__99914b932b   has status   UNKNOWN
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=041929279, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4476) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed scheduling:
    - 1 SquaredNumbers()

Did not run any tasks
This progress looks :( because there were tasks whose scheduling failed

===== Luigi Execution Summary =====

P.S I am new to both Python and Luigi.

**Comment by dlstadther** [comment]
closing this issue. 

- [ ] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [x] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Comment by snenkov** [comment]
For what it's worth, this helped me: https://stackoverflow.com/questions/43968574/python-luigi-copy-to-postgres
