### ISSUE TITLE
ExternalProgramTask can't process external process printing unicode to stdout

### ISSUE THREAD

**Issue by cappelll** [spotify/luigi#2327]
As the title says, ExternalProgramTask crashes with the following error when the external task prints some unicode in stdout:

> Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 191, in run
>    new_deps = self._run_get_new_deps()
>  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 129, in _run_get_new_deps
>    task_gen = self.task.run()
>  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/external_program.py", line 110, in run
>    logger.info('Program stdout:\n{}'.format(stdout))
>UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 35: ordinal not in range(128)

My pipeline orchestrates a number of bash scripts. I can't share nothing of the actual code, but I have created some code that reproduces the issue.
This is the smallest task that recreated the issue

    import luigi
    from luigi.contrib.external_program import ExternalProgramTask

    class MyExternalProgramTask(ExternalProgramTask):

        my_script = luigi.Parameter()
        my_output = luigi.Parameter()

        def output(self):
            return luigi.LocalTarget(self.my_output)

        def program_args(self):
            return [self.my_script, self.my_output]

    if __name__ == "__main__":
        luigi.run()

(save it and name it my_bug_example.py).
The following are two very simple bash scripts that write to an output file and print something to stdout:

ascii_stdout.sh

    #!/bin/bash
    echo "Just a place holder for possible output" > $1
    echo "Hi guys, this is a ascii message"

unicode_stdout.sh

    #!/bin/bash
    echo "This is a unicode message: removed ‘wav.scp’ "
    echo "Hi guys, this is a ascii message"

Running the following command will trigger the error:

    python my_bug_example.py MyExternalProgramTask --local-scheduler --my-script ./unicode_stdout.sh --my-output unicode.out

While this one will run smootly:

    python my_bug_example.py MyExternalProgramTask --local-scheduler --my-script ./ascii_stdout.sh --my-output ascii.out

I'm pretty confident that the bug is locate in line [110](https://github.com/spotify/luigi/blob/master/luigi/contrib/external_program.py#L110) of external_program.py:

    logger.info('Program stdout:\n{}'.format(stdout))

with the following change also the unicode case should work:

    logger.info(u'Program stdout:\n{}'.format(stdout))

Of course, the same modification should be applied also to line [113](https://github.com/spotify/luigi/blob/master/luigi/contrib/external_program.py#L113) of external_program.py.

**Comment by eandreev** [comment]
Due to a customer request, we have to stick with python 2.7 in our project. This error pops up when we get an error message from an external command in utf-8.

Unfortunately, it's not possible to run a python2.7 spark job from a python 3.x luigi. Also, we have to run a localized Linux distro, so most of the console errors produce utf-8 characters.

Please fix it so it runs under both python 2.x and puthon 3.x or provide a way to fix it.

So far, I will resort to manually fixing the code myself.

**Comment by jethron** [comment]
Since 718a48aea491690f74feb9e0e0b6b5ee8082341c you should be able to specify `capture_output = False` in your task class; that should avoid the logging call and let your task work correctly.

Maybe luigi should consider using `from __future__ import unicode_literals` to make the Python2 <> Python3 compatibility a bit more predictable? It's a bit heavy-handed though, and might cause more issues with Python2 -- but it would also have solved this issue, rather than special-casing these two literals as unicode.
