### ISSUE TITLE
[contrib.kubernetes] Hangs on 'Pod errors: Unschedulable'

### ISSUE THREAD

**Issue by yonromai** [spotify/luigi#2334]
When asking for more resources (e.g. CPU) than the Kubernetes cluster can allocate, Kubernetes fails the job (rightfully) with a status `Pod errors: Unschedulable`.

The `KubernetesJobTask` logic, however, fails to catch this error and hangs:
```
DEBUG: Kubernetes job example-luigi-b8ffbfbbeb7b429bb8cc1e81c6a879c9 is still running
DEBUG: Kubernetes job example-luigi-b8ffbfbbeb7b429bb8cc1e81c6a879c9 is still running
DEBUG: Kubernetes job example-luigi-b8ffbfbbeb7b429bb8cc1e81c6a879c9 is still running
...
```
(FWIW, I'm using GKE here)

**Comment by yonromai** [comment]
@mcapuccini ^

**Comment by mcapuccini** [comment]
Hi @yonromai. Thanks for reporting the issue. The problem should on this block of code: https://github.com/spotify/luigi/blob/6ce970846c0ca8c2850bc168b686340e15982b2b/luigi/contrib/kubernetes.py#L160-L171, which only checks for pod status "running", "succeeded" and throws error for everything else. I think that `pykube`, the library that we are currently using for the Kubernetes Task, returns running when the pod is unschedulable, and that you need to run an additional command to query the unschedulable status. Unfortunately I don't have time to work on it at the moment, but since you are getting the error in one of your settings, it could be a nice contribution if you could sort it out. I'd be happy to review and merge your patch 🙂 .

**Comment by yonromai** [comment]
@mcapuccini thanks for coming back to me. 

I took a look at it yesterday, I think the problem might rather be in the `self.__get_job_status()`. 
I played with it and printed the contents of `pod.obj['spec']`, `node.obj['spec']` and `job.obj`. All of these objects had the same data whether the job was actually scheduled or not (because too much resources was requested). 
Also,  `node.unschedulable` was `False` in both cases.

I'm wondering if the problem could be with pykube/GKE compatibility.
