### ISSUE TITLE
namedtuples can not be used as parameters

### ISSUE THREAD

**Issue by alexkamp** [spotify/luigi#2409]
hey, 

I am trying to use namedtuples in a list parameter, but I get an error, which indicates that the named tuple is somehow transformed into a normal tuple. 

Example code:

```
import luigi, os

import collections
Person = collections.namedtuple('Person', ['fname', 'lname'])


class TestTask(luigi.Task):
	file = luigi.Parameter(default="hello.txt")
	persons = luigi.ListParameter()
	
	def run(self):
		with self.output().open(mode='w') as out:
			for person in self.persons:
				out.write("Hello {} {}\n".format(person.fname, person.lname))
	
	def output(self):
		return luigi.LocalTarget(os.path.join("bugout", self.file))


class AllTests(luigi.WrapperTask):
	
	def requires(self):
		yield(TestTask(persons=[Person(fname='Colton', lname='Haynes'), Person(fname='Connor', lname='Franta')]))


if __name__ == "__main__":
	luigi.run(main_task_cls=AllTests, local_scheduler=True)


```

The expected result would be a file named 'bugout/hello.txt' which contains 

```
Hello Colton Haynes
Hello Connor Franta

```

in fact, I get

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.6/site-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "bug.py", line 14, in run
    out.write("Hello {} {}".format(person.fname, person.lname))
AttributeError: 'tuple' object has no attribute 'fname'
```

If I replace the luigi.ListParameter() with luigi.Parameter(), it works as expected. 

EDIT: 

As it may be important:

```
> pip3 show luigi
Name: luigi
Version: 2.7.2
Summary: Workflow mgmgt + task scheduling + dependency resolution
Home-page: https://github.com/spotify/luigi
Author: The Luigi Authors
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: python-daemon, tornado
```

This is on Mac OS 10.13.4

**Comment by petedmarsh** [comment]
I had a quick look into this - you're right that the namedtuples get converted into tuples, this happens because `ListParameter` recurses down through each item in the list and converts list/tuple parameters to `tuples` via a call to `_recursively_freeze`  (see: https://github.com/spotify/luigi/blob/4133f2739fa0b5b56e3f0d5f3de62fdf8971b604/luigi/parameter.py#L846) - as namedtuples subclass `tuple` they get converted back into regular tuples too.

I think the only way to support `namedtuples` as you would like would be to subclass `Parameter` with a custom `NamedTupleParameter` which would work a little bit like `EnumParamater` (see: https://github.com/spotify/luigi/blob/4133f2739fa0b5b56e3f0d5f3de62fdf8971b604/luigi/parameter.py#L774).
