### ISSUE TITLE
Priority doesn't work

### ISSUE THREAD

**Issue by gamebusterz** [spotify/luigi#2443]
I am calling a wrapper task which has the following dependencies:   
1. `TaskA(),TaskB(),TaskC(arguments1=['arg1'],arguments2=['arg1','arg2'])]`
I though Luigi would be executing these tasks in a sequence, starting with TaskA. But that doesn't run as expected. 

2. Next, I tried declaring the priority using a @property decorated function, which returned the value of a `priority_value` parameter.  

`TaskA(priority_value=10),TaskB(priority_value=5),TaskC(arguments1=['arg1'],arguments2=['arg1','arg2'],priority_value=1)]`  

```
@property
	def priority(self):
		return self.priority_value
```  
3.  I also tried the simple `priority` parameter 

`TaskA(priority=10),TaskB(priority=5),TaskC(arguments1=['arg1'],arguments2=['arg1','arg2'],priority=1)]`   

But none of these work. 

While running the tasks , Luigi checks completion in the desired order,  
Checking if TaskA is complete,  
Checking if TaskB is complete,  
Checking if TaskC is complete ,

But then goes right into TaskC and starts checking for its dependencies and executing them.

**Comment by gamebusterz** [comment]
@Tarrasch

**Comment by Gmousse** [comment]
If I m right, priority doesn't guaranty task order. Refers to https://github.com/spotify/luigi/blob/master/doc/tasks.rst#task-priority.

It's more like it orders task attribution to workers.
Example:
- If you work with 3 workers, your 3 tasks will run in parallel.
- If you have 2 workers, Task A will run first, Task B will run in parallel.
Then Task C will run when one worker will be free.

I m maybe wrong.

If you need to run your task in a sequence, you must use `requires` https://github.com/spotify/luigi/blob/master/doc/tasks.rst#task-priority. It's the only "secure" way I know to run your tasks in the good order.

**Comment by gamebusterz** [comment]
@Gmousse Yes, I am using requires, but I am specifying multiple tasks in requires.

I guess you're saying specifying only one task at a time in requires?

**Comment by Gmousse** [comment]
The case I met in my job:
- TaskA requires TaskB and TaskC
- TaskB is not directly dependent of TaskC but must be executed after the TaskC

Then you need this order: TaskC -> TaskB -> TaskA

It's wrong to consider than TaskA can require both TaskB and TaskC and then order their execution with the priority (as I described previously, it's not safe with multiple workers).

You must have: TaskA requires TaskB. TaskB requires TaskC.
By this you will be sure that TaskC will be executed before TaskB.

**Comment by gamebusterz** [comment]
Cool, thanks @Gmousse for the clarification. I guess that means priority in Luigi is useless, because this is the only case where one would require the use of priority.

**Comment by Gmousse** [comment]
@gamebusterz There are some usecases where priority is useful:

You have a workflow of tasks containing different families of tasks:
- A type of Task used to compute data used in your webapp (Example: playlist prefered by users)
- A type of Task to report user actions on your webapp (Example: data used to train machine learning models)
- A type of Task to compute some informations about your business

The three family of tasks are unrelated (directly and indirectly).

But the first task family has higher priority (because it's used directly in your webapp by real users).

You workflow looks like:

````python

class MyBusinessWorkflow(luigi.Task):

    requires(self):
         yield ComputeUsersActions() # priority 60
         yield ComputeUsersPlaylists() # priority 100
         yield ComputeBusinessReport() # priority 20
````

It means luigi will execute firstly the highest priority. But if you have multiple workers, luigi will not wait highest priority task is done.

Priority is just used to organise unrelated tasks execution, not to give a precise order.

**Comment by gamebusterz** [comment]
That explains it. Thanks a lot Guillaume :)
