### ISSUE TITLE
RangeDailyBase warns for parameter not set

### ISSUE THREAD

**Issue by pettersoderlund** [spotify/luigi#2514]
When I use Rangedailybase I always get a warning for parameter not set.

```
C:\Program Files (x86)\Python36-32\lib\site-packages\luigi\parameter.py:261: UserWarning: Parameter "param_name" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value)

```

Looked at https://github.com/spotify/luigi/issues/1810 and tried adding email to conf 
https://github.com/spotify/luigi/issues/1810#issuecomment-258284082
but it did not help... 

Everything else is working fine! 

I'm running luigi on windows.

**Comment by dlstadther** [comment]
The warning is not so much that `param_name` is not set, as much as it is a `Parameter` with a default of `None`. `Parameter`s are being treated as if they're `StringParameter`s and thus should have a default of `''`. Since then, a new parameter type has been introduced which accepts `None` as a valid default value, `OptionalParameter`.

Regardless, this is merely a warning and shouldn't negatively impact the execution of your pipelines.

Feel free to submit a PR to default `param_name` to an empty string or to an OptionalParameter.

**Comment by pettersoderlund** [comment]
The description of param_name in https://github.com/spotify/luigi/blob/7d3bf2e06981391007d7ac923ae638ade96d8dcc/luigi/tools/range.py#L109

says that 
```
param_name = luigi.Parameter(
        default=None,
        description="parameter name used to pass in parameterized value. Defaults to None, meaning use first positional parameter",
        positional=False)
```

I don't get the point of this parameter -- seems like some kind of blockage of using positional parameters or what? Would it lose its function dfaulting to empty string or optionalParameter?

> Defaults to None, meaning use first positional parameter

**Comment by dlstadther** [comment]
That [`param_name` was added in 2015](https://github.com/spotify/luigi/pull/1240/files), by @joeshaw 

Looks to me like `param_name` can be updated to an [`OptionalParameter`](https://github.com/spotify/luigi/blob/master/luigi/parameter.py#L331-L348) without the need to change any other code.
