### ISSUE TITLE
Interpolation fails for list parameters

### ISSUE THREAD

**Issue by yuriy-davygora** [spotify/luigi#2573]
Hello,

I have a problem when using Luigi 2.8.0 (Python 2.7.15). If I have a parameter which is a list, instead of a string, the interpolation fails with

`File ".../lib/python2.7/site-packages/luigi/configuration/cfg_parser.py", line 73, in _interpolate_env
    match = self._ENVRE.search(value)
TypeError: expected string or buffer`

Apparentely, the _interpolate_env method does not account for possible list parameter.

### Minimal reproducing example ###

1. Create a virtualenv or a Conda env with Python 2.7.15 and Luigi 2.8.0

2. Create a file called `test.py` with the following contents:
```
#!/usr/bin/env python

from luigi import configuration, Task, ListParameter


config = configuration.get_config()


class TestTask(Task):
    list_param = ListParameter(config_path={'section': 'test', 'name': 'list_param'})


config.set('test', 'list_param', ['item1', 'item2'])
test_task = TestTask()
```

3. Run this file from the above mentioned environment.

Thank you for considering this issue report!

**Comment by dlstadther** [comment]
@iamlikeme Given you added the support for Environment Variable interpolation (and that's where this error is occurring), could you give this a look?

Thanks

**Comment by iamlikeme** [comment]
I have reduced the example to the following:

```
from luigi import configuration
config = configuration.get_config()
config.set('test', 'list_param', ['item1', 'item2'])
```

I tested this snipped with luigi 2.7.9, i.e. before environment interpolation was added, and it works in Python 2.7 but not in Python 3.6. The reason is that in Python 3 `ConfigParser.set` method requires option values to be strings (see [docs](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.set)). This was not the case in Python 2.

It seems that it has never been possible to save list parameters to cfg-config in Python 3, so the envvar interpolation does not introduce a breaking change.

I suggest to patch envvar interpolation to make Python 2 behavior backward-compatible, and to leave Python 3 behaviour as is (i.e. calling `config.set` with a list option raises TypeError). Does it make sense, @dlstadther?

**Comment by yuriy-davygora** [comment]
@iamlikeme Wouldn't that mean, that, although the ListParameter class is there, there will be actually no way to have list-valued parameters?

**Comment by iamlikeme** [comment]
So I looked into [Luigi docs for ListParameter](https://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.ListParameter) and it says that list parameters should be formatted as JSON strings. This pretty much solves the problem for both Python 2 and 3 and works with interpolation:

```python
# luigi 2.8.0, Python 2.7.15
import os
from luigi import configuration, Task, ListParameter

class TestTask(Task):
    list_param = ListParameter(config_path={'section': 'test', 'name': 'list_param'})

config = configuration.get_config()
config.set('test', 'list_param', '["item1", "item2"]')  # Value is a JSON array

TestTask().list_param  # Returns (u'item1', u'item2')

os.environ["ENVVAR"] = "foo"
config.set('test', 'list_param', '["${ENVVAR}", "item2"]')  # Value is a JSON array with reference to an envvar
TestTask().list_param  # Returns (u'foo', u'item2')
```

**Comment by yuriy-davygora** [comment]
@iamlikeme Thank you very much for the information!
