### ISSUE TITLE
Task\Workflow: Why are run twice?

### ISSUE THREAD

**Issue by diegocorradini** [spotify/luigi#2633]
I see this behavior in my pipeline.
The question was already asked, however I do not understand why it works like that.

Is there a workaround?
Otherwise I have some logic inside the tasks which is run twice.

**Comment by dgronskij** [comment]
Could you elaborate more on this? The task succeed's / marked as 'DONE' and then is re-run? Does it have something with not holding `task.complete() == True` condition after first successful run?

**Comment by diegocorradini** [comment]
Hi thanks for your answer.
I have to say that I am using sciluigi then the syntax is sometime different.

Anyway yes, the task succeds as done, and then is re-run after a while.

**Comment by dgronskij** [comment]
@diegocorradini I'm not familiar with `sciluigi`, however, in vanilla `luigi` this may take place due to absence of output targets after the first run. That said, if you define a task `A` with a target and after successful run the targets still do not exist, when executing a task `B` depending on `A`, the worker will check the completeness of `A` and will see that dependency does not hold hence will rerun `A`. But in the same vanilla luigi, after that the worker will check again the dependency and it will raise an exception on "Unfulfilled dependency at run time" if the task `A.complete()` is still not `True`.

**Comment by diegocorradini** [comment]
This make sense.. 

With _sciluigi_ syntax I am running a workflow which generates multiple tasks.
However, the WorkflowTask class does not have any target output implementation.
Then maybe this is the reason because run two times.

   
    class Workflow(sciluigi.WorkflowTask):

        def workflow(self):
            // this code is run twice
            tasks = []
            mates = self.get_input()
            for mate in mates:
                wf = self.new_task('sampleWF', SubWorkflow)
                tasks.append(wf)
            return tasks

Since it is a wrapper, do you think there is a way to signal that the WorkflowTask is complete?

Many thanks for your help

**Comment by dgronskij** [comment]
@diegocorradini, I looked  into `sciluigi`, your `workflow` method is called inside luigi's  `luigi.Task.requres` method. Not the `run` one.  Apperently this has nothing to do with what I supposed above and it's not the `luigi`s stuff. The best option I see is either to delve in the code and find the root of the problem  or raise the question in the corresponding `sciluigi` issue tracker.
