### ISSUE TITLE
A bug in the luigi.cfg when using DEFAUL values.

### ISSUE THREAD

**Issue by snenkov** [spotify/luigi#2660]
I encountered the following issue when using the `luigi.cfg` with a `[DEFAULT]` section.
Below is an example of my `luigi.cfg`

```
[DEFAULT]
MAIN_HERO = IronMan
SIDE_KICK = Batman

[SomeLuigiTaskName]
super-hero = %(SIDE_KICK)s
side-kick = Robin
```

When I execute this, I expect that for `SomeLuigiTaskName` the parameter `super-hero` is set to `Batman` and the parameter `side-kick` is set to Robin.
Instead what happen is that the parameter `super-hero` is set to the desired variable `Batman`, but because the `DEFAULT` variable name is the same as the parameter variable in `SomeLuigiTaskName`, the name `side-kick` is `SomeLuigiTaskName` is also changed to `Batman`.

If I have other luigi tasks with the same parameter names, they will be changed as well.

I tried to figure out how the configparser is configured, but could not. I know that the case sensitivity is the default one, which is case-insensitive. But why it overwrites parameters is not understood.

**Comment by dlstadther** [comment]
@snenkov  Could you provide sample code related to the parameter value overridding you're seeing?

As far as normal ConfigParser interpolation, your values should be interpreting correctly. But i cannot speak to `Instead what happen is that the parameter super-hero is set to the desired variable Batman, but because the DEFAULT variable name is the same as the parameter variable in SomeLuigiTaskName, the name side-kick is SomeLuigiTaskName is also changed to Batman` without understanding this scenario better

**Comment by rayrrr** [comment]
Not sure it's related, but any config key with `-` spacers in the name instead of `_` spacers hold major wonk potential because `-` is a first-class operator in Python for the subtraction operation. In Python, `side-kick` always means "the contents of the variable `side` minus the contents of the variable `kick`. Luigi may be doing some magic under the hood to cast `-` to `_` in Python contexts, which would explain the behavior you are seeing. Workaround: pretend `-` and `_` are the same thing and uniquely name your config keys accordingly.
