### ISSUE TITLE
Configuration default-scheduler-port doesn't seem to take effect

### ISSUE THREAD

**Issue by guidopetri** [spotify/luigi#2742]
With the following `luigi.cfg` file:

    [core]
    default-scheduler-port=8083

and running `luigid` with no CLI args, it seems the visualizer is on port 8082 anyway. This can be fixed by running `luigid --port 8083`, but it doesn't seem like expected behavior.

**Comment by charlesoblack** [comment]
Looks like this was an issue way back in 2017 with #2235 but was closed by stale-bot. I can't figure out myself why this setting is ignored.

**Comment by charlesoblack** [comment]
Alright, I suspect it has to do with : https://github.com/spotify/luigi/blame/95f903f4f4d2c997e57255feb5354422c9f2b270/luigi/cmdline.py#L34

and possibly:

https://github.com/spotify/luigi/blob/95f903f4f4d2c997e57255feb5354422c9f2b270/luigi/process.py#L77

and maybe:

https://github.com/spotify/luigi/blob/95f903f4f4d2c997e57255feb5354422c9f2b270/luigi/server.py#L157

The first loads the config from the CLI, but apparently never from the `.cfg` file. The latter two have the port defaulting to 8082. Would we have to change how the luigid command works exactly? Maybe @soxofaan can comment since apparently you committed that originally?

**Comment by charlesoblack** [comment]
I'd also appreciate input from @dlstadther here :)

**Comment by dlstadther** [comment]
I haven't dove into the code, but rather the [tests](https://github.com/spotify/luigi/blob/master/test/server_test.py#L287-L450). It appears the chunk which tests setting the server with different non-default port (8083) does not run on Travis and so it seems likely to me this could have been broken.

**Comment by charlesoblack** [comment]
Sorry, I'm getting a little lost in the nested classes - would it be `test_ping()` that you're referring to? Any clue why it was disabled on Travis?

**Comment by soxofaan** [comment]
> Maybe @soxofaan can comment since apparently you committed that originally?

FYI I din't commit/write that originally, I just moved that code around in 95f903f4f4d2c (March 2015).
Originally, the port option was added by 60ea09f5d461 (July 2014)

But anyway, I don't think this matters that much here

**Comment by dlstadther** [comment]
@charlesoblack yes, but for the children `INETProcessServerTest` (run) and `INETLuigidServerTest ` (cmdline)

Looks like @Tarrasch disabled them overtime due to sporadic Travis failures; unsure if that would still be the case now.

**Comment by charlesoblack** [comment]
I think we're still waiting on @Tarrasch to comment on this.

**Comment by Tarrasch** [comment]
I think this isn't working because at some point I tried to separate the config system from the scheduler program `luigid`. I think it's good to have them separate, it brings us closer to having the scheduler potentially being able to run in another language. Well, at least the idea of it.

**Comment by charlesoblack** [comment]
I see... @dlstadther should I just start a "in progress" PR for this that enables the tests? And then figure out how to make it work again?

**Comment by charlesoblack** [comment]
I think I'd still like to keep this issue open.
