### ISSUE TITLE
Trigger event on upstream failure

### ISSUE THREAD

**Issue by ThePletch** [spotify/luigi#2781]
Several of our workflows that run through Luigi post a notification to an external system when the workflow succeeds or fails, but there is currently no straightforward way to notify the user if a dependency of the root task fails, preventing the root task from running.

Options we've explored include:
1. Tying the hook to post the failure notification to every component task's `on_failure` (difficult to both prevent duplicate notifications and allow for multiple failure notifications for multiple attempts)
2. Associating a custom hook that deduplicates alerts by their root task (requires tracking a task's 'root task', does not fully eliminate above problem with allowing multiple notifications for different runs)

The option that would require the least work from us would be an event that triggers the first time an upstream task for a specific task fails. This would let us keep all configuration for notifying about successes and failures in the root workflow, rather than needing to manage notifications for every step in the process and handle the accompanying usability features (deduplication, etc).

Is this something that's available in Luigi, but I'm unaware of, something that's slated for development soon, or is there a technical limitation preventing this from being easily implemented?

**Comment by ThePletch** [comment]
Correct. An option to configure specific events triggered by a task to 'bubble up' the dependency chain would be ideal.

**Comment by kwilcox** [comment]
I agree that this would be a nice built-in addition.

We have implemented a solution such that every task has a `build_tag` (really a `pipeline_tag`, it identifies a unique pipeline run) that is passed down to child tasks. Instead of yielding/returning Tasks directly, Tasks call `self.call_task` instead, which just overloads the parameters passed down. I've simplified into the the example below. We actually have many more parameters that are passed "downstream" other than the `build_tag` most of which give child tasks more context about where it came from.

```python
def gen_tag():
    return "{:08x}".format(random.getrandbits(32))

class BaseTask:
    build_tag = luigi.Parameter(default=gen_tag(), significant=True)
    notification = luigi.BoolParameter(default=False, significant=False)

    def call_task(self, task, *args, **kwargs):
        return task(*args, build_tag=self.build_tag, **kwargs)

class Task(luigi.Task, BaseTask):
    pass

class WrapperTask(luigi.WrapperTask, BaseTask):
    pass

class RootTask(WrapperTask):
    notification = luigi.BoolParameter(default=True, significant=False)
```

We then manage the failure/success of each task in Redis (using `build_id:[timestamp]` as a key) and ultimately only notify when a task fails/succeeds that has `notification=True`. The first Task to have `notification=True` reads all of the data from Redis with the same `build_id`, sorts and cleans up the data, and sends out notifications. By default a `RootTask` does this, but you can also pass in the `notification=True` parameter to any task to have it notify.
