### ISSUE TITLE
AttributeError: 'str' object has no attribute 'date_a'

### ISSUE THREAD

**Issue by gabriel-aranha** [spotify/luigi#2825]
I couldn't find any examples online using the DateIntervalParameter in conjunction with luigi.build() to see if it is wrong.
Here is the relevant part of my task: 
```
class AggregateData(luigi.Task):
        date_interval = luigi.DateIntervalParameter()

        def requires(self):
                return SourceData(some_other_parameter)

        def output(self):
                return luigi.LocalTarget(path='some_path')

        def run(self):
                date_a = self.date_interval.date_a
                date_b = self.date_interval.date_b
                df = df.loc[date_a:date_b]
                .
                .
                .
if __name__ == '__main__':
        luigi.build([AggregateData(date_interval="2016-10-30-2016-11-30")])
```
When I execute the pipeline using the build command like it is presented above, I get the title error.
When i simply run the pipeline using the command line and passing the command below, it works as expected.
```
PYTHONPATH='.' luigi --module pipeline AggregateData --local-scheduler  --date-interval '2016-10-30-2016-11-30'
```
It seems that the DateIntervalParameter is not parsing the date when I use the build command from inside the code.

**Comment by ihowell** [comment]
That is correct. That would be because when the attribute is coming from the command line, it will accept that the input has already been stringified and thus needs to convet it to the proper date_interval class. However, when you are passing from within Python, luigi assumes that you are passing in the parameter as an date interval object and thus does not attempt to parse any string.

To fix this, you should import `Custom` from the `date_interval` module. Then use:
```
AggregateData(date_interval=Custom.parse("2016-10-30-2016-11-30"))
```

Or, you can just create a date-interval object directly by passing in two dates.

**Comment by gabriel-aranha** [comment]
Now I understand. It worked correctly. Thank you.
