### ISSUE TITLE
How to trigger task by REST API ? 

### ISSUE THREAD

**Issue by ttpro1995** [spotify/luigi#2884]
According to docs https://luigi.readthedocs.io/en/stable/execution_model.html#triggering-tasks  
It use crontab to trigger task.

However, is there any other way to trigger the task like REST API (http) yet ?

**Comment by Tarrasch** [comment]
You probably are looking for a crontab replacement, so that a luigi-client (in Python) is started somehow.

**Comment by ttpro1995** [comment]
is it recommand to start Luigi from command line by another program ? 

for example in Java 

` p = Runtime.getRuntime().exec("/home/meow/anaconda3/bin/luigi --scheduler-port 9991 --module me.meow.TheCatTask    me.meow.TheCatTask.FeedDryFood    --workers 0 &>   $LOG/dryfood.log");`

**Comment by ihowell** [comment]
Yes, that works. Luigi itself tries to avoid the problem of knowing when to start (essentially scheduling Luigi) so that you can do it however you want or need to. Basically, anything goes! Also, you don't have to worry about running tasks with the exact same parameters concurrently if you are using the central scheduler.
