### ISSUE TITLE
luigi re-runing tasks

### ISSUE THREAD

**Issue by Bcjg23** [spotify/luigi#2925]
Hi all,
I am new to luigi and I have some tasks to create a RDS instance in AWS (CreaInstanciaRDS), another to create schemas (CreaEsquemasBD) for the database and a 3rd task to create the tables in the schema (CreaTablasBD). But every time I run the *main* task -which I understand is the task that creates the tables-, all the required tasks also run again. 
I am using complete() method in all tasks since any of them return a file.

![Screenshot from 2020-04-02 22-23-42](https://user-images.githubusercontent.com/54872638/78324287-8432f200-7531-11ea-80bd-73c8c264d899.png)
![Screenshot from 2020-04-02 22-23-48](https://user-images.githubusercontent.com/54872638/78324286-8301c500-7531-11ea-810a-ea5691a7c58d.png)
![Screenshot from 2020-04-02 22-24-16](https://user-images.githubusercontent.com/54872638/78324284-81380180-7531-11ea-8e70-fc94b5307b04.png)

Thanks in advance!

**Comment by charlesoblack** [comment]
Since your Task gets garbage collected at some point, the `self.task_complete` attribute gets reset to `False`.

Maybe you could instead check if your instances already exist in AWS, and define `complete(self)` using that? Otherwise, I imagine the best thing to do is have a temporary file to write to...

**Comment by Bcjg23** [comment]
Thanks a lot. I think I will save a temporary file to avoid Luigi running the tasks again.

**Comment by charlesoblack** [comment]
@dlstadther I think we can close this issue. :)

**Comment by RaresI** [comment]
Hello,

Completed tasks should most probably not get garbage collected, as that destroys their precious state, as well the assumption that a task with the same significant parameters is the same object.
The complete() method can potentially be quite expensive to compute, and completed task may also have valuable information which was computed and stored as state.
TaskProcess.run checks the completion of deps right before running the task, so a new empty instance is *always* created right after termination, and forcing complete to be evaluated again from scratch. If the completion persistence check is done using the network, that is simply doubles requests.
My recommendation is to keep completed tasks in memory until the end of all tasks and not allow to be garbage collected. That should improve performance significantly and simplify the programming model.

**Comment by charlesoblack** [comment]
In this case, the OP is re-running tasks after they're all done. That's why
they don't get recognized as complete.

**Comment by RaresI** [comment]
Hell

> In this case, the OP is re-running tasks after they're all done. That's why they don't get recognized as complete.

Hi. It is not re-running them, but it is re-instancing them in order to check their completion status. If that return true the story ends, if it returns false it fails with in worker.run with "Unfulfilled %s at run time: %s'
The task register is an amazing feature and this bug invalidates the entire feature.

Can we please either reopen this issue or continue the conversation on #2935?
