### ISSUE TITLE
Flaky behavior when using S3Target

### ISSUE THREAD

**Issue by kronion** [spotify/luigi#2967]
I have a small Luigi pipeline (~50 tasks) that writes outfiles to S3 using `S3Target`. The pipeline is executed daily. Every few weeks (say 2-4 weeks), I see tasks fail with tracebacks like this:

```
Traceback (most recent call last):
  File "/home/.cache/pypoetry/virtualenvs/venv-9TtSrW0h-py3.7/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: MyTask_2020_06_30
```

This exception indicates that the worker is trying to run a task that doesn't have all its requirements complete. However, when I check on the dependencies, I find that they are all indeed complete, with outfiles in S3 as expected. Whenever I see tasks fail this way, they succeed without any modification the next time they execute. It seems that essentially any task in my pipeline can fail in this manner. There's no apparent pattern.

I thought that there could be a lag between when the upstream task writes its outfile to S3 and when the the outfile is seen to exist in the `complete()` call. I added a 5 second sleep to the outfile creation like so:
```
    def write_to_output(self, data=None):
        with self.output().open("w") as outfile:
            if data:
                outfile.write(data)
            else:
                outfile.write(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        # Add a delay to give S3 time to actually display the file?
        # Hopefully this resolves the numerous race conditions we've seen.
        time.sleep(5)
```
Unfortunately, the errors persist.

Using Luigi version 2.8.12. I have a central scheduler with two worker nodes.

**Comment by lallea** [comment]
You are probably bitten by S3's lack of consistency, not by Luigi. S3 does not give any guarantees that you can immediately read an object that you have written. In really bad cases, it can take many hours for them to be visible.

IIRC, this presentation gives some explanation: https://youtu.be/UOE2m_XUr3U. Spark's Delta Lake was created as a workaround for weak storage consistency. GCS and HDFS provide stronger guarantees.

I suggest closing this issue.

**Comment by kronion** [comment]
Thanks for the response. I suppose I could try to read the object back in my function instead of sleeping.

I didn't realize S3 consistency behavior was so poor. I think it begs the question, should Luigi even have an `S3Target` class, if it's not reliable for workers to check?

**Comment by lallea** [comment]
The particular problem that you experience is not a major problem. The job will fail, but it will probably succeed the next time it is executed, assuming that you run Luigi through some cron scheduling. The pipeline then heals by itself, so it makes sense to have an S3Target. On closer thought, this scenario can happen with GCS as well, but probably not as often.

The major problem with S3 is that it lacks listing consistency. It does not affect S3Target, but S3FlagTarget. If the producer writes data files, and then the flag file (_SUCCESS), a consumer that has seen the flag file is not guaranteed to be able to list all the files. GCS and HDFS does provide this guarantee, but S3 does not.

I guess we should add documentation to Luigi, since these issues are likely to bite Luigi users. They are present in most distributed systems, but many developers are not aware.

**Comment by kronion** [comment]
Since opening this issue, S3 has added strong read consistency: https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

These errors no longer occur as a result.
