### ISSUE TITLE
Warnings when used with Python 3.10

### ISSUE THREAD

**Issue by marhoy** [spotify/luigi#3148]
When used with Python 3.10, I get the following warnings:

```
luigi/target.py:287: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version

luigi/worker.py:161: DeprecationWarning: Seeding based on hashing is deprecated since Python 3.9 and will be removed in a subsequent version.
```

**Comment by alecgarza96** [comment]
Instances of randrange found in target.py
![image](https://user-images.githubusercontent.com/43724421/157110404-6bc50311-a64f-4950-87bd-9df59afeea63.png)
![image](https://user-images.githubusercontent.com/43724421/157110491-e074c290-0bed-4716-8f2d-bea4555ef099.png)

**Comment by alecgarza96** [comment]
Assuming this error is being generated due to the scientific notation being used to represent 10,000,000,000. Will test this out.

**Comment by alecgarza96** [comment]
For the second warning, it appears the issue lies here:
![image](https://user-images.githubusercontent.com/43724421/157111687-fcfa3586-b6ce-4ac7-927d-4e2ff0e650eb.png)


I wrote some basic test code and was able to successfully replicate and resolve error

![image](https://user-images.githubusercontent.com/43724421/157111786-6e88a65b-c723-445d-881f-3b3aeb739d74.png)

**Comment by alecgarza96** [comment]
Able to replicate second warning with following code
![image](https://user-images.githubusercontent.com/43724421/157120238-7b4d303f-b5dd-4169-b5c2-2b869071721d.png)

1e10 = ten billion

remedied with following code

![image](https://user-images.githubusercontent.com/43724421/157120360-4afea187-aaef-4412-81e9-9c70f48cf145.png)

**Comment by alecgarza96** [comment]
https://github.com/spotify/luigi/pull/3150

submitted pull request above
