### ISSUE TITLE
pandas dataframe as output

### ISSUE THREAD

**Issue by lim-0** [spotify/luigi#3160]
Hello guys. my question is whether I can ues dataframe but not not a file like csv as output,?
Here's an example of what I intend to do.

```
class PrintNum(luigi.Task):
    df = None
    n = luigi.IntParameter(default=5)
    lt = list()

    def requires(self):
        return []

    def output(self):
        return [self.df]

    def run(self):
        data = [[4, 7, 10],
                [5, 8, 11],
                [6, 9, 12]]

        self.df = pd.DataFrame(data, columns=['A', 'B', 'C'])


class SquareNum(luigi.Task):
    n = luigi.IntParameter(default=10)
    def requires(self):
        return [PrintNum()]

    def output(self):
        return luigi.LocalTarget('success.csv')

    def run(self):
        # self.input()
        self.input()['A'] = self.input()['A'].map(lambda x: x+1)
        self.input().to_csv("success.csv")
```

but it seems invalid:

Traceback (most recent call last):
  File "/root/miniconda3/envs/dm2/lib/python3.7/site-packages/luigi/worker.py", line 173, in run
    missing = [dep.task_id for dep in self.task.deps() if not dep.complete()]
  File "/root/miniconda3/envs/dm2/lib/python3.7/site-packages/luigi/worker.py", line 173, in <listcomp>
    missing = [dep.task_id for dep in self.task.deps() if not dep.complete()]
  File "/root/miniconda3/envs/dm2/lib/python3.7/site-packages/luigi/task.py", line 571, in complete
    return all(map(lambda output: output.exists(), outputs))
  File "/root/miniconda3/envs/dm2/lib/python3.7/site-packages/luigi/task.py", line 571, in <lambda>
    return all(map(lambda output: output.exists(), outputs))
AttributeError: 'str' object has no attribute 'exists'

what can i do,to deal with that?

**Comment by lallea** [comment]
No, Luigi schedules jobs that read persisted datasets and write persisted datasets. You should either persist your dataframe to storage, or keep it in memory and collapse the two steps to one.

**Comment by lim-0** [comment]
> No, Luigi schedules jobs that read persisted datasets and write persisted datasets. You should either persist your dataframe to storage, or keep it in memory and collapse the two steps to one.

Thank you! but,I seems to find a method to soluve this:
I definded a target like this：
```
class DataframeTarget(luigi.Target):
    def __init__(self, df):
        self.df = df

    def exists(self):
        lines = len(self.df)
        return True if lines > 0 else False
```

then it works：
```
class Task1(luigi.Task):
    df = pd.DataFrame()

    def requires(self):
        return []

    def output(self):
        return DataframeTarget(self.df)

    def run(self):
        data = [[4, 7, 10],
                [5, 8, 11],
                [6, 9, 12]]

        self.df = pd.DataFrame(data, columns=['A', 'B', 'C'])
        # print(self.df)
        time.sleep(2)
        self.df.to_csv("sucess.csv", index=False)
        print("taskA ,success! at {}".format(datetime.datetime.now()))
```

**Comment by lallea** [comment]
Yes, you can make it work. But from your example, it is not clear what you would gain. You might as well collapse the tasks.

It might make sense if you share the output or PrintNum with multiple downstream tasks. But this is not how Luigi is meant to work, and dataframes are not great to share, since they are mutable. That being said, if it works for you and does what you need, go ahead. Luigi's main strength is its simplicity, and simple components are easy to adapt to whatever you might need. :-)

**Comment by lim-0** [comment]
> Yes, you can make it work. But from your example, it is not clear what you would gain. You might as well collapse the tasks.
> 
> It might make sense if you share the output or PrintNum with multiple downstream tasks. But this is not how Luigi is meant to work, and dataframes are not great to share, since they are mutable. That being said, if it works for you and does what you need, go ahead. Luigi's main strength is its simplicity, and simple components are easy to adapt to whatever you might need. :-)


Thank you for your advice, which is very helpful to me. I want to build a data mining platform, so I use Luigi to build pipes, each Luigi. Task is an algorithm component, so using dataframe is the best way I think, I don't know if there is a better way, if you can give me some suggestions, it will be very helpful for me。

**Comment by lallea** [comment]
Apologies for slow response.

Luigi's primary mode of operation is to orchestrate processes, potentially
running on different machines, creating datasets stored in shared storage.
You may choose to use it in a different mode, but it is useful to know the
implications.

If a Task creates a Target that cannot be observed by other luigi
processes, there is risk of confusion. The process that created the target
will inform the central scheduler that it is now done. The central
scheduler may then give permission to another process to run a task that
depends on the created target. But that process cannot see the target and
will be confused and abort.

The problem above can happen both with in-memory targets, as in your case,
and with targets on storage that is not shared, e.g. a local filesystem.
You can take responsibility to avoid these problems. For example, you can
run all your luigi processes on one machine, where they share the local
filesystem. Or you can decide to only ever run one luigi process at a time,
and use --local-scheduler. If you do the latter, your dataframe passing
will probably work fine.

There are valid use cases for using these tricks for partial pipelines,
e.g. if sub-minute latency is important for some pipeline. I had one client
who had to run part of a pipeline on a specific windows machine because
graphics drivers. In that case, there was no reason to store intermediate
datasets on shared storage.

Luigi is not very opinionated, for good and bad. This means that you are
free to choose operating model, but it also places burden on you to
understand and choose between tradeoff points.

I hope this is helpful. Let us know if there are further questions.

Lars Albertsson
Data engineering entrepreneur
www.scling.com
+46 70 7687109
https://twitter.com/lalleal, https://www.linkedin.com/in/larsalbertsson/
