### ISSUE TITLE
A dependency failed does not cause job fail cascade

### ISSUE THREAD

**Issue by BusyJay** [spotify/luigi#331]
For example, job A require job B, job B require job C. If job C fail, job B fail of course. However, job A will not fail. In fact, it won't be run. And it outputs:

> There are 1 pending tasks possibly being run by other workers

This behavior makes it hard to write a job with fault tolerance because A is never be run or triggered any event.

A quick work around is to change a line of code in function get_work, which is in scheduler.py, from

```
elif self._tasks[dep].status != DONE:
```

to

```
elif self._tasks[dep].status not in (DONE, FAILED):
```

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
