### ISSUE TITLE
Hadoop version configuration is not delivered to nodes

### ISSUE THREAD

**Issue by rocha** [spotify/luigi#333]
The function `get_hdfs_syntax` in the `luigi.hdfs` module tries to read the hadoop version from the `luigi` configuration. However, the configuration file, or the value of the version is not send by `luigi` to the worker nodes.

The configuration can be copied to the nodes using another channel, however it would be nice if `luigi` takes cares of it. It is specially useful in setups like AWS EMR.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
