### ISSUE TITLE
Exception adding worker - scheduler might be running an older version

### ISSUE THREAD

**Issue by aldanor** [spotify/luigi#390]
I was wondering what could be causing this exception:

``` sh
Exception adding worker - scheduler might be running an older version
Traceback (most recent call last):
  File "envs/bdl/lib/python2.7/site-packages/luigi/worker.py", line 301, in _add_worker
    self._scheduler.add_worker(self._id, self._worker_info)
```

when trying to do something like this:

``` python
task = RootTask()
sch = RemoteScheduler(host=host, port=port)
while not task.complete():
    w = Worker(scheduler=sch, worker_processes=workers)
    w.add(task)
    w.run()
    w.stop()
    time.sleep(10)
```

I can't seem to really figure out what's the reason. I'm running a `luigid` scheduler (same version as luigi I'm using, obviously) on the same box. `RootTask` is basically a meta-task which lists other tasks as requirements, writes a dummy text file in `run()` and has a `LocalPath` pointing to this file as `output()`. All of the downstream tasks seem to complete just fine, but the root task never gets to writing this dummy file because of the exception above, so although the task is technically done, its `task.complete()` is never true.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
