### ISSUE TITLE
Use of mutable default values in HadoopJobRunner (and others)

### ISSUE THREAD

**Issue by onlynone** [spotify/luigi#391]
Many of the arguments to the constructor of `HadoopJobRunner` use mutable default values: https://github.com/spotify/luigi/blob/master/luigi/hadoop.py#L312. This means, for example, if you kick off a job that depends on a bunch of other jobs, they'll all get the same `jobconfs` object, then if one of them updates its `jobconfs` property, they'll all be updated.

See: http://pylint-messages.wikidot.com/messages:w0102

I would suggest using something like:

```
    def __init__(self, streaming_jar, modules=None, streaming_args=None, libjars=None, libjars_in_hdfs=None, jobconfs=None, input_format=None, output_format=None):
        self.streaming_jar = streaming_jar
        self.modules = modules or []
        self.streaming_args = streaming_args or []
        self.libjars = libjars or []
        self.libjars_in_hdfs = libjars_in_hdfs or []
        self.jobconfs = jobconfs or {}
        self.input_format = input_format
        self.output_format = output_format
        self.tmp_dir = False
```

I would have submitted a diff, but since this same issue likely exists in other spots across the code base, I thought you might want to review whether, and where this should happen globally rather than just patching it in one spot.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
