### ISSUE TITLE
Indirect Require by Data Path

### ISSUE THREAD

**Issue by rudaoshi** [spotify/luigi#420]
In my system, we split system with several component, with Data path interface between each other.

The virtual of this design is to avoid long dependency and improve the reusability of tasks.

We build a control task, that start all tasks in all component. In the begining, tasks of some component  begin to run, and tasks in depending components is held on. It is reasonable because the data they needed has not been produced yet. 

However, when all the dependent components are finished and the data are produced, the task is still in  holding status. 

Is it possible to automatic start the task when their required data is produced ？

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
