### ISSUE TITLE
Luigi workers should report dead workers to scheduler

### ISSUE THREAD

**Issue by a1k0n** [spotify/luigi#443]
This is a frequent annoyance:
INFO - 2014-09-11 16:02:49,449 - JobThing(date=2014-09-10, build=2014-W32) is currently run by worker Worker(salt=178277472, host=edgenode-a1.spotify.net, username=as, pid=22199)

If the hostname of the worker doing the scheduler check is the same host reported as the worker currently running the job, the least it could do is see if the pid is still alive and if not, report it dead to the scheduler and rerun the task.

That, or provide some sort of command line tool to tell the scheduler it's dead. Because right now I have no recourse but to wait for some unknown timeout; I can't use --local-scheduler or stuff will go awry.

**Comment by Tarrasch** [comment]
Actually this is a great idea to make luigi more responsive. Although I think the added complexity might not be worth it. The pinging works fine enough I believe.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
