### ISSUE TITLE
add input file name and line number to error message

### ISSUE THREAD

**Issue by amnonkhen** [spotify/luigi#459]
In tasks that have a file-like input, some lines can cause an error during their processing, e.g. encoding, unexpected type. It would be useful to have informative message in the log that include the offending file name and line number.

Would such a thing be implemented in FileWrapper?
Is it the responsibility of Task extensions to take care of it?

**Comment by themalkolm** [comment]
I can't imagine how it is possible to solve this problem a generic way. The exceptions are raised by various decoders and luigi has nothing to do with them, right?

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Comment by Tarrasch** [comment]
> This is kind of by design and not a bug.
 
What themalkolm said

**Comment by themalkolm** [comment]
@Tarrasch wooot! This themalkolm must be very smart to say something like this!
