### ISSUE TITLE
mkdir error when using HdfsClientCdh3

### ISSUE THREAD

**Issue by imazor** [spotify/luigi#520]
Hi, 

I am using the following config:

[hadoop]
version: apache1
streaming-jar: /opt/mapr/hadoop/hadoop-2.4.1/share/hadoop/tools/lib/hadoop-streaming-2.4.1-mapr-1408.jar
python-executable: /usr/bin/python

[hdfs]
client: hadoopcli

When executing the following task:

class Streams(Task):
    ''' Faked version right now, just generates bogus data.
    '''
    date = DateParameter()

```
def run(self):
    with self.output().open('w') as output:
        for i in xrange(1000):
            output.write('{a} {b} {c}\n'.format(
                a=random.randint(1, 999),
                b=random.randint(1, 999),
                c=random.randint(1, 999)))

def output(self):
    return hdfs.HdfsTarget(self.date.strftime('/user/user_name/hadoop/learn_luigi/data/streams_%Y_%m_%d_faked.tsv'))
```

I am getting the following error:

Runtime error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/luigi/worker.py", line 76, in run
    self.task.run()
  File "top_artists.py", line 19, in run
    with self.output().open('w') as output:
  File "/usr/lib/python2.6/site-packages/luigi/hdfs.py", line 708, in open
    return self.format.pipe_writer(HdfsAtomicWritePipe(self.path))
  File "/usr/lib/python2.6/site-packages/luigi/hdfs.py", line 602, in **init**
    mkdir(parent_dir, parents=True, raise_if_exists=False)
TypeError: mkdir() got an unexpected keyword argument 'parents'

looks like based on my config, the hdfs client is HdfsClientApache1() which inherits from 
HdfsClientCdh3.

the mkdir function defined for the parent class taking only 1 arg : path
however while trying to open hdfs target (using HdfsAtomicWritePipe), the **init** try to execute the following:
mkdir(parent_dir, parents=True, raise_if_exists=False)
as a result the error.

Also would be nice if  -p option will be added to the mkdir in HdfsClientCdh3.

BTW, is there preferred config for the hdfs client (in the config file) for using Mapr ?

Thanks.

**Comment by mfcabrera** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

**Comment by mfcabrera** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.
