### ISSUE TITLE
Problem to check the existing of a Hive partition

### ISSUE THREAD

**Issue by ChingChien** [spotify/luigi#704]
I am using "HivePartitionTarget" and ran into a problem that Luigi mis-identified a non-existing partition as existing... 
I traced the hive.py code and it looks the problem comes from 
https://github.com/spotify/luigi/blob/master/luigi/hive.py#L135

I am thinking the stdout format may different from Hive setting and different Hive version.
Hence, perhaps there should have additional verification like the table 
https://github.com/spotify/luigi/blob/master/luigi/hive.py#L130

**Comment by erikbern** [comment]
If you can repro the issue, would be great if you can put together a pull request. Even better, if it comes with a unit test :)

**Comment by timchurch** [comment]
I ran into a similar issue as well today.  In my case, this seems to be due to the hive property `hive.cli.print.header=true`

I will try to put together a fix and submit a pull request.

**Comment by Tarrasch** [comment]
Thanks! @timchurch

**Comment by mfcabrera** [comment]
- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
