### ISSUE TITLE
Latest Luigi version breaks my hadoop jobs

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#738]
I used to be able to initialize a class like

```
class MyStreamingJob(luigi.hadoop.JobTask):
    param = luigi.Parameter()
```

with code like

```
MyStreamingJob('param_value')
```

but now this results in an error

```
luigi.parameter.MissingParameterException: MyStreamingJob[args=('param_value',), kwargs={}]: requires the 'param' parameter to be set
```

I believe it's now interpreting the first argument as pool, where it never did that before.

**Comment by erikbern** [comment]
Thanks – this seems to be the case. I don't know why our existing tests aren't catching it. Let me try to add a test + fix

**Comment by Tarrasch** [comment]
You still have broken backwards compatibility when you removed `if not p.is_global`. We had issues when the condition is only `if p.significant` (we had a insignificant global parameter in a Task). I thought to change it to `if p.significant and not p.is_global`. I'll send a PR with tests tomorrow. Why was is `if not p.is_global` removed in the first place by the way?

**Comment by erikbern** [comment]
We can probably add back `if not p.is_global` – I was on a spree to delete as much of global parameter usage as possible. But if it causes issues let's add it back

**Comment by erikbern** [comment]
You are right that it's not fully backwards compatible. The reason I chose to go ahead and do it is that afaik `is_global` wasn't even documented so I didn't think anyone would use it

**Comment by Tarrasch** [comment]
Well, missing test cases have been costly this time then. :)

Perhaps just change it back to the very original `if not p.is_global` rather than the almost random `if p.significant and not p.is_global`?

On the other hand, we want to eventually remove `is_global`. Without breaking this particular case of `luigi.hadoop.JobTask`. So maybe `if p.significant and not p.is_global` is the way to go? I'll make sure to add test cases so the next code change will be more conscious.

**Comment by erikbern** [comment]
Yeah that sounds great. Are you planning to implement it? Let me know either way

**Comment by Tarrasch** [comment]
I will fix this first thing tomorrow.
