### ISSUE TITLE
A wrapper for a wrapper checks all dependencies twice

### ISSUE THREAD

**Issue by rathboma** [spotify/luigi#77]
In the following setup:

``` python
Wrapper1(WrapperTask):
    requires(self):
        Wrapper2()

Wrapper2(WrapperTask):
    requires(self):
        [a for a in a_bunch_of_stuff()]
```

Dependencies of Wrapper2 will be checked twice, once when evaluating Wrapper1, once when evaluating Wrapper2

Example log output:

``` bash
Checking if Wrapper1 is complete
Checking for flag at /a/b/c/_SUCCESS # dependency of Wrapper2
... # more checks
Scheduled Wrapper1
Checking if Wrapper2 is complete
Checking for flag at /a/b/c/_SUCCESS # same check again!
... # repeated checks
Scheduled Wrapper2
```

This isn't a bug pre-se, but more a behavior that can really slow stuff down if dependency checking takes a while (like when talking to hive).

**Comment by kretes** [comment]
I think this is the same situation as described in https://groups.google.com/forum/#!topic/luigi-user/2mpzIjqgpQA and that it touches not only a wrapper task but all tasks in general. Solution from  	@erikbern  ''we should even enforce that a task isn't successful unless all its outputs exist" is the best one - 
it will make a check first and if it is successfull there will be no more checks. if the first check was not successful a task will be run and a check after that will be performed to ensure the task was successful and that will be it. no more double/triple/.. checking.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
