### ISSUE TITLE
Did python 3 refactoring break backwards compat?

### ISSUE THREAD

**Issue by Tarrasch** [spotify/luigi#786]
Spotify just noticed a type error like this.

```
Traceback (most recent call last):
  File " ... ", line 433, in test_nulls
    result = job.test_run(records)
  File "/usr/lib/python2.6/dist-packages/spotify/luigi/hadoop.py", line 421, in test_run
    print >> f, l
  File "/usr/lib/python2.6/dist-packages/luigi/mock.py", line 143, in write
    BytesIO.write(self2, data)
TypeError: expecting a bytes object, got unicode
```

@gpoulin, you did a lot of nice improvements and refactorings regarding the way FileTargets, can you immediately see if a stack trace like this can be related?

**Comment by jooon** [comment]
Extremely likely, since it says BytesIO. Those lines were StringIO before. However. I don't understand which commit id of luigi/mock.py has BytesIO.write(self2, data) on line 143. There has been changes since then.

It could either be a plain bug.

It could be unintended regression. Things are correct now, but they were bad before.

However, a file write should always take a str in python 2, but for backward compatible reasons it will of course accept unicode and when needed translate it to str with the default encoding which is ascii, but is unfortunately overridden to be utf-8 for almost all Spotify python code. At Spotify, many bugs are hidden because of this. If that is the case, the more explicit "print >> f, l.encode('utf-8')" is the fix.

**Comment by gpoulin** [comment]
@Tarrasch It's indeed my fault sorry. I did test on this with the file target because I wasn't sure it would still work (it worked) but overlooked the mock. I'll try to push a PR really soon. However I agree with @jooon (will explain more on this later).

**Comment by gpoulin** [comment]
@Tarrasch the fix is here. I'm only putting it in for backward compatibility because It's pretty bug prone to implicitly write unicode into a file. That's probably the main reason why I use python3 (it doesn't let you do that). I would suggest that you implicitly encode your data or that you use `luigi.format.UTF8` on your target.

I also tried to wrap the BytesIO in a io.BufferedRWPair, which would have give a more file like behavior, but there was some issue with blocking/non-blocking mode which is not super well documented in python doc.

I'll try to create a `TargetTestBase` to make sure that the different targets (that accept byte stream) have a consistent interface.

**Comment by gpoulin** [comment]
Python 2.6 start to be annoying (https://travis-ci.org/spotify/luigi/jobs/52077787#L739) :P. I come with a fix.

**Comment by gpoulin** [comment]
Just to be sure to not be misinterpreted. I didn't intend to break unicode because I think it's bad to write unicode to file. I just overlooked the MockFile. I'll try to be more careful on this. I will add more tests with unicode literal.

**Comment by Tarrasch** [comment]
Haha, totally chill @gpoulin. We're super happy for all your contributions! We all make coding mistakes from time to time. Again, thank you very much! :)
