### ISSUE TITLE
Still encoding issues with 2.6

### ISSUE THREAD

**Issue by Tarrasch** [spotify/luigi#790]
Hi @gpoulin, do you directly see what could be wrong in this kind of stack trace? It seems to be related to encoding so I ping you again. :)

```
 Traceback (most recent call last):
16:57:24   File "/«PKGBUILDDIR»/test/client_event_test.py", line 16, in test_valid_line
16:57:24     output = task.test_run([input_line])
16:57:24   File "/usr/lib/python2.6/dist-packages/spotify/luigi/hadoop.py", line 421, in test_run
16:57:24     print >> f, l
16:57:24   File "/usr/lib/python2.6/dist-packages/luigi/format.py", line 321, in write
16:57:24     self._stream.write(self._convert(b))
16:57:24   File "/usr/lib/python2.6/dist-packages/luigi/format.py", line 328, in _convert
16:57:24     b = b.encode(self.encoding)
16:57:24 UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 564: ordinal not in range(128)
```

This is a bit more worrying than the previous stack trace because it doesn't seem to be related to the testing code.

**Comment by gpoulin** [comment]
@Tarrasch 

####Short answer
Change this https://github.com/spotify/luigi/blob/master/luigi/format.py#L502 to:
```python
MixedUnicodeBytes = MixedUnicodeBytesFormat('utf-8')
```

It might give unexpected result for user that don't have utf-8 system but I think itSs what expect 99% of Luigi's user.

####Long answer
It was working before??? Is there some monkey-patching somewhere? This happen because you try to write non-ascii character on a system that have `locale.getpreferredencoding()` equal ascii (the default on linux on python2 for some strange reason). However the same issue should have happen with the old code, unless some monkey patching on the file object. The previous code was equivalent to:
```python
f = file('test', 'w')
f.write('é') // raise UnicodeEncodeError
f.close()
```

**Comment by gpoulin** [comment]
@Tarrasch Is this still an issue?

**Comment by Tarrasch** [comment]
No. We managed to fix this :)
