### ISSUE TITLE
New Tornado RPC prevents scheduling from completing successfully

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#824]
If I schedule a large number of jobs, I always get weird errors like

```
  File "luigi/worker.py", line 575, in _add_worker
    self._scheduler.add_worker(self._id, self._worker_info)
  File "luigi/rpc.py", line 171, in add_worker
    return self._request('/api/add_worker', {'worker': worker, 'info': info})
  File "luigi/rpc.py", line 104, in _request
    page = self._fetch(url, body, log_exceptions, attempts)
  File "luigi/rpc.py", line 84, in _fetch
    lambda: self._async_fetch(full_url, body)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 388, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
TimeoutError: Operation timed out after None seconds
```

The errors go away if I schedule my jobs in smaller batches. They have also gone away since reverting 9752ba7e81d0a49a51f1fbcc55f8db0a84d31b81 "Use tornado AsyncHTTPClient for the rpc".

**Comment by erikbern** [comment]
That's strange. We should fix. Might make sense to revert for now

**Comment by oldpa** [comment]
This also fails for me since I haven't got tornado installed on the cluster

**Comment by gpoulin** [comment]
It might be due to some issue with mixing threading and tornado IOLoop. The scheduler is used within the keep-alive thread meaning that two `run_sync` call could be done at the same time to the same IOLoop. Based on my understanding of tornado event loop, that's bad. Creating the `SimpleAsyncHTTPClient` just before the request would solve the issue (if I'm right). The http client would be associated with the thread IOLoop and the described issue couldn't occur. However I'm in favor of a revert here. It seemed neat for the testing to use the Tornado httpclient however, I would rather go with the save option and use the urllib client (If it wasn't from dependency issues I would requests thou).

@oldpa Tornado is hard [dependency](https://github.com/spotify/luigi/blob/master/setup.py#L44). Maybe it shouldn't and the client should be separated from the server. However this is the kind of issue you should expect when running a package without all its hard dependencies installed.

@Tarrasch (when your back) @erikbern, should snakebite be a hard dependency? Currently, it's just use for hdfs optimization and unit testing.

**Comment by erikbern** [comment]
Let's revert it then. Can I go ahead and do it?

I don't think Snakebite should be a hard dependency, but I don't think it matters if Tornado is

**Comment by themalkolm** [comment]
That would explain why my tornado tasks sometimes timeout without any sensible reason. Do I need to just nuke snakebite to do not have these problems?

**Comment by erikbern** [comment]
I don't think snakebite has anything to do with these problems?

**Comment by themalkolm** [comment]
Haven't read carefully, sorry.

**Comment by erikbern** [comment]
Ok, what's the kind of issues you have seen?

**Comment by erikbern** [comment]
was this resolved?

**Comment by themalkolm** [comment]
UPD from me. We simply created our own loop and it either fixed everything or somebody broke our email error notifications. No errors since.

**Comment by erikbern** [comment]
what did you mean with your own loop?

**Comment by daveFNbuck** [comment]
Looks like this was resolved by 0bc0097eda5a9f467b4e1667b134ebe4b97d4426. I haven't tried it yet, so I'll deploy today and verify that everything's working before closing this issue.

**Comment by erikbern** [comment]
awesome – let me know if you still see the issue!

**Comment by daveFNbuck** [comment]
The issue is resolved. Sorry I forgot to mention it until now.

On Wed, Mar 18, 2015 at 8:38 AM, Erik Bernhardsson <notifications@github.com
