### ISSUE TITLE
Custom date interval behavior confusing

### ISSUE THREAD

**Issue by grivescorbett** [spotify/luigi#868]
The `Year`, `Week`, `Month` and `Day` date interval types all add one extra day to the end date so that the date interval is inclusive on the beginning date and exclusive on the end date.  This makes a lot of sense and lets me easily write code like this:

```python
class KPIReport(luigi.Task):
    date_interval = luigi.DateIntervalParameter()

    def run(self):
        start = datetime.datetime.combine(self.date_interval.date_a, datetime.time())
        end = datetime.datetime.combine(self.date_interval.date_b, datetime.time())
        num_members = User.find({'signup_time': {'$gte': start, '$lt': end}}) 
        # etc...
```
So now if I run ```python reports.py KPIReport --date-interval 2015-03-20``` everything works out and I get a report for that single day.

However now if I want to run the same report on an arbitrary range, such as the last 7 days, I might think I can simply run ```python reports.py KPIReport --date-interval 2015-03-14-2015-03-20```.  But now instead of ending at 23:59:59 on the 20th my date interval ends at 23:59:59 on the 19th.  

It seems to me that the `Custom` date interval should add one day to the end date just as all of the other implementations do, or is there a different best practice for this scenario?

**Comment by erikbern** [comment]
This is by design. There are some particular reasons:

1. If you think of a date itself not as an extent in time but as a timestamp then 2012-03-20 is equal to 2012-03-20T00:00:00 which is the 0th second of 2012-03-20. 
2. In a lot of situations it's a lot more convenient to express it as half open intervals because you don't have to think about how many days are in a month. For instance if you run a bimonthly report then it's easier to run it for 2012-02-01-2012-02-15 and 2012-02-15-2012-03-01 rather than 2012-01-01-2012-02-14 and 2012-02-15-2012-02-29 (now you need to know the number of days of Feb 2012)

**Comment by erikbern** [comment]
Found some web sites on the topic btw:
http://stackoverflow.com/questions/4264947/what-is-best-practice-for-representing-time-intervals-in-a-data-warehouse
http://wrschneider.blogspot.com/2014/01/time-intervals-and-other-ranges-should.html

**Comment by erikbern** [comment]
Also compare how Python uses half-open notation for array slicing (R doesn't though, afaik)
