### ISSUE TITLE
Luigi doesn't check default arguments when deciding whether a job is already running

### ISSUE THREAD

**Issue by boosh** [spotify/luigi#873]
I have a job with a `date` CLI argument that defaults to yesterday. It's cronned to run daily.

However, if there's a problem with the job and it doesn't terminate for one day, then the next day when the command is run, luigi reports that the job is already running, when in fact it isn't because the `date` parameter will now be different.

E.g.:

The job is invoked on 2015-03-30 with `my-job --another-arg=blah`. The date parameter is not explicitly passed so defaults to the day before, 2015-03-29. This job fails and retry logic keeps it around.
The next night, 2015-03-31, cron executes `my-job --another-arg=blah` again, and this time the `date` parameter defaults to the value 2015-03-30. Luigi should run this job but it doesn't. Instead it reports that the job is already running and exits. 

Obviously the fix for now is to explicitly pass the `date` parameter, but really luigi should calculate the values of all default values before deciding whether a job is already running or not.

**Comment by mfcabrera** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue if the problem still persists.
