### ISSUE TITLE
SQLAlchemyTarget only works with single SQLAlchemy engine

### ISSUE THREAD

**Issue by dylanjbarth** [spotify/luigi#979]
I have a `ProcessDataTask(sqla.CopyToTable)` that processes some data and inserts it to `schemaA.TableA`. That task requires `BackupTask(sqla.CopyToTable)`, which copies Table A and inserts it into `schemaB.tableA_backup1` before the processing task dumps new data in. Both tasks return `SQLAlchemyTarget`s as output -- but because the targets are in different schemas, the one that get's defined first is where my backup is written. In other words, because `ProcessDataTask` creates a class level attribute `_engine` for the first schema, I can't have my backup task point at a different schema (unless I'm missing something, which is likely/possible). 

@gouthambs Happy to look at possible fixes and submit a PR if this is a priority or something you want to see fixed -- please correct me if I've overlooked something here or wasn't clear in my explanation.

**Comment by gouthambs** [comment]
@dylanjbarth You have explained the issue very well. The `_engine` is a class variable to avoid creation of multiple engine instances. But the side effect of this is that one cannot use multiple schemas. 

If you have some ideas on fixing this issue, please take a stab at it. I can give you pointers if you need help.

One approach I can think of in order to address this issue is to replace `_engine` with `_engine_dict` which will store a `dict` of engine instances. The trick is then to chose an appropriate `key` for the `dict` and connect them intelligently with the task. Hope this helps!

**Comment by dylanjbarth** [comment]
@gouthambs yeah the dict approach seems sensible. what do you think of this? https://github.com/dylanjbarth/luigi/commit/f026abc295defe0094381aac14011fc5e9d01558?diff=unified

Just using the connection string for the key, since that will be specified on a task by task basis and it's unique to the engine instance. Also, I subtracted storing the pid -- I wasn't too sure if there was a need for that anymore, let me know what you think.

sqla_tests are passing for me locally, happy to look at adding a test for multi-tables if you think this is in the right direction.

**Comment by gouthambs** [comment]
@dylanjbarth The engine as a dict looks good. The `pid` logic is necessary in the multiprocessing scenario. I added that to address issues I was encountering in a production scenario with multiple processes. Unfortunately the tests don't always capture it I think. Issue #821 also mentions an issue which the `pid` logic fixes. Can you put the `pid` logic back?

**Comment by dylanjbarth** [comment]
ah, yep sure thing. Potentially dumb question: is the process ID meant to be associated with each individual engine object or with the SQLAlchemyTarget? My guess is with the Target but wanted to double check to make sure.

**Comment by gouthambs** [comment]
Let me give you a bit of background on the `pid` logic.

The `SQLAlchemyTarget` keeps a reference to the `_engine` object and process ID where the `_engine` object was created. In the multiple workers scenario, I have noticed `SQLAlchemyTarget` instances with a ` _engine` reference to an object created in a different process. Since you cannot share the `SQLAlchemy engine` across processes, we have to recreate the `_engine` instance for each worker process. That is essentially what we are trying to do there by checking against the current process ID. 

If engines are created after the process forking then this should not be a problem and we could potentially do away with the `pid` checking logic. What I observed was that the engine object is created and then the other processes seem to get copies with a stale `_engine` reference.  

To answer your question, the process ID is meant to be associated with each `_engine` object. We just check if the current process id is the same as the process where the engine was created before using the engine object.

Hope this helps!

**Comment by dylanjbarth** [comment]
thanks for the background info, makes sense. How about something like this? https://github.com/spotify/luigi/compare/master...dylanjbarth:master 

Basically just creating a unique engine_id by combining the connection string and pid to use as the key.

**Comment by gouthambs** [comment]
:+1:  looks good to me. @Tarrasch What do you think?

**Comment by Tarrasch** [comment]
Well, I don't know anything about SqlAlchemy really. So I'm not the right person to comment. :)

My only code-wise comment is that the engine_id should be a structured value, one should prefer `("conn_string", 1234)` over `"conn_string_1234"`. Even better with a NamedTuple maybe?

**Comment by erikbern** [comment]
sounds good!

**Comment by gouthambs** [comment]
@Tarrasch @dylanjbarth 
In order  to avoid the stale connection issue I mentioned above, we can have then `_engine` store using a key = connection_string and value = (engine_object, process_id). The check for the engine would look something like

    pid = os.getpid()
    connection = SQLAlchemyTarget._engine_dict.get(self.connection_string)
    if (connection is not None) or (pid != connection[1]):
        # create and reset connection
        engine = sqlalchemy.create_engine(...)
        SQLAlchemyTarget._engine_dict[self.connection_string] = (engine, pid)
    return engine


Even when we use tuples as keys, the original issue of stale tuples ("conn_string", some_other_pid) will linger in the dict. This could potentially grow large in multiple processor, multiple schema use cases.

**Comment by Tarrasch** [comment]
Yea just use NamedTuple over code like `connection[1]`. :)

**Comment by dylanjbarth** [comment]
Good thinking, updated to fit the `{conn_string: (engine, pid)}` structure, using a namedtuple for pythonicness  -- https://github.com/spotify/luigi/compare/master...dylanjbarth:master thoughts?

**Comment by Tarrasch** [comment]
Thoughts? I'm just thinking how awesome collaboration you two guys have had @dylanjbarth and @gouthambs! :)

Just add a test case, squash the commits and send away a PR and let Travis run the CI build matrix. Sounds good?

**Comment by gouthambs** [comment]
@dylanjbarth I like the change. The named tuple makes the code more readable. Good call @Tarrasch . One small suggestion, can we move the 

    Connection = collections.namedtuple("Connection", "engine pid")
to a class level definition? This will avoid repeated definition of the named tuple for every `engine` call!

**Comment by dylanjbarth** [comment]
@gouthambs well spotted, will find some time today to fix it up and add a test 

@Tarrasch haha cool! Thanks to all of you for all your hard work on luigi. We started using it at work a couple of months ago and we're into it. Happy to help contribute back, least we can do. @colemast and I will be giving an intro talk on Luigi at PyData London in a few weeks as well, spreading the word :+1:

**Comment by Tarrasch** [comment]
Cool! Be sure to link to it the slides from our README. :)

**Comment by dylanjbarth** [comment]
@gouthambs are you ok with this mega-simple test case? https://github.com/dylanjbarth/luigi/commit/a069369cb7f1da47c0d4c64baed9d8fed7ff415c

**Comment by gouthambs** [comment]
:+1: This covers the part you added. Can we add a few more lines to make sure both the engines actually perform the copy task? Small mod like this should test the data as well:

    def test_multiple_engines(self):
        """
        Test case where different tasks require different SQL engines.
        """
        alt_db = "sqlite:///%s" % os.path.join(TEMPDIR, "sqlatest2.db")

        class MultiEngineTask(SQLATask):
            connection_string = alt_db

        tas0, task1, task2 = BaseTask(), SQLATask(), MultiEngineTask()
        self.assertTrue(task1.output().engine != task2.output().engine)
        luigi.build([task2, task1, task0], local_scheduler=True, workers=self.NUM_WORKERS)
        self._check_entries(task1.output().engine)
        self._check_entries(task2.output().engine)

**Comment by dylanjbarth** [comment]
Thanks for all the guidance @gouthambs & @Tarrasch looking forward to continuing to contribute

**Comment by gouthambs** [comment]
@dylanjbarth Was great working with you. Thanks for contributing back! This is a great improvement that will potentially benefit other users.
