### ISSUE TITLE
Execution should begin in parallel with scheduling

### ISSUE THREAD

**Issue by jcoveney** [spotify/luigi#98]

**Comment by Tarrasch** [comment]
This is not implemented yet. Maybe it will be one day. In the meantime users can use assistants as they will pull down tasks immediately.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
